// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (C) 2026 Pranay Kiran
//
// POLYGON (issue #23). A regular n-gon is an ordinary closed polyline, so the only
// thing worth testing hard is the rule that turns a centre, a reference point and a
// side count into vertices -- and that the rubber band and the committed polyline are
// generated by the SAME rule (core::polygon_vertices), so what is dragged out is what
// lands.

#include <algorithm>
#include <cmath>
#include <string>
#include <vector>

#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>

#include "musacad/command/command_processor.hpp"
#include "musacad/core/command.hpp"
#include "musacad/core/polygon.hpp"

using namespace musacad::core;
using Catch::Approx;

namespace {
struct SilentOutput : musacad::command::CommandOutput {
    void append_line(const std::string&) override {}
    void set_prompt(const std::string&) override {}
};
struct ProcHarness {
    std::vector<Command> cmds;
    SilentOutput out;
    musacad::command::CommandProcessor proc{
        [this](Command c) { cmds.push_back(std::move(c)); }, nullptr, out};

    [[nodiscard]] const AddPolylineCommand& poly() const {
        return std::get<AddPolylineCommand>(cmds.at(0));
    }
};

/// The length of every side, which must be equal for a regular polygon.
std::vector<double> side_lengths(const std::vector<Vec2>& v) {
    std::vector<double> out;
    for (std::size_t i = 0; i < v.size(); ++i) {
        out.push_back(length(v[(i + 1) % v.size()] - v[i]));
    }
    return out;
}
} // namespace

TEST_CASE("#23: an inscribed polygon touches the circle at its vertices") {
    // Inscribed: the reference point IS a vertex, so every vertex is exactly `dist`
    // from the centre.
    const std::vector<Vec2> v = polygon_vertices({0, 0}, 10.0, 6, /*inscribed=*/true, 0.0);
    REQUIRE(v.size() == 6);
    for (const Vec2& p : v) {
        REQUIRE(length(p) == Approx(10.0));
    }
    REQUIRE(v[0].x == Approx(10.0)); // the reference direction (angle 0) is a vertex
    REQUIRE(v[0].y == Approx(0.0).margin(1e-12));
    // Regular: all six sides equal.
    for (double s : side_lengths(v)) {
        REQUIRE(s == Approx(10.0)); // a hexagon's side equals its circumradius
    }
}

TEST_CASE("#23: a circumscribed polygon touches the circle at its edge midpoints") {
    // Circumscribed: `dist` is the APOTHEM, so the reference direction hits the middle
    // of an edge, and the vertices are further out than dist.
    const std::vector<Vec2> v = polygon_vertices({0, 0}, 10.0, 6, /*inscribed=*/false, 0.0);
    REQUIRE(v.size() == 6);
    const double circum = 10.0 / std::cos(kPi / 6.0);
    for (const Vec2& p : v) {
        REQUIRE(length(p) == Approx(circum));
    }
    // The midpoint of the first edge sits at the apothem, in the reference direction.
    const Vec2 mid{(v[0].x + v[1].x) * 0.5, (v[0].y + v[1].y) * 0.5};
    REQUIRE(length(mid) == Approx(10.0));
    REQUIRE(mid.y == Approx(0.0).margin(1e-9));
    REQUIRE(mid.x == Approx(10.0));
}

TEST_CASE("#23: the polygon follows the reference direction instead of snapping to an axis") {
    const double a = kPi / 5.0;
    const std::vector<Vec2> v = polygon_vertices({3, 4}, 7.0, 5, true, a);
    REQUIRE(v.size() == 5);
    // The first vertex lies exactly along the reference angle from the centre.
    REQUIRE(v[0].x == Approx(3.0 + 7.0 * std::cos(a)));
    REQUIRE(v[0].y == Approx(4.0 + 7.0 * std::sin(a)));
    const std::vector<double> s = side_lengths(v);
    for (double len : s) {
        REQUIRE(len == Approx(s[0])); // still regular when rotated
    }
}

TEST_CASE("#23: fewer than three sides is not a polygon") {
    REQUIRE(polygon_vertices({0, 0}, 10.0, 2, true, 0.0).empty());
    REQUIRE(polygon_vertices({0, 0}, 10.0, 0, true, 0.0).empty());
    REQUIRE(polygon_vertices({0, 0}, 0.0, 6, true, 0.0).empty()); // nor is zero size
}

TEST_CASE("#23: POLYGON commits a CLOSED polyline of n vertices") {
    ProcHarness h;
    h.proc.submit_line("POL");
    h.proc.submit_line("5");    // sides
    h.proc.submit_line("0,0");  // centre
    h.proc.submit_line("I");    // inscribed
    h.proc.submit_line("10,0"); // radius point
    REQUIRE(h.cmds.size() == 1);
    const AddPolylineCommand& p = h.poly();
    REQUIRE(p.closed);           // a polygon is a closed shape, not an open chain
    REQUIRE(p.points.size() == 5); // n vertices, NOT n+1 with a repeated first
    for (const Vec2& v : p.points) {
        REQUIRE(length(v) == Approx(10.0));
    }
}

TEST_CASE("#23: POLYGON's Circumscribed option makes a bigger polygon than Inscribed") {
    const auto build = [](const char* fit) {
        ProcHarness h;
        h.proc.submit_line("POLYGON");
        h.proc.submit_line("6");
        h.proc.submit_line("0,0");
        h.proc.submit_line(fit);
        h.proc.submit_line("10,0");
        return h.poly().points;
    };
    const std::vector<Vec2> ins = build("I");
    const std::vector<Vec2> cir = build("C");
    REQUIRE(ins.size() == 6);
    REQUIRE(cir.size() == 6);
    REQUIRE(length(cir[0]) > length(ins[0])); // circumscribed reaches past the circle
    REQUIRE(length(ins[0]) == Approx(10.0));
    REQUIRE(length(cir[0]) == Approx(10.0 / std::cos(kPi / 6.0)));
}

TEST_CASE("#23: POLYGON's Edge option builds the polygon on one given side") {
    // Two picks are one SIDE: a square on the edge (0,0)-(10,0) must have that exact
    // side, four equal sides, and sit above the edge (to its left).
    ProcHarness h;
    h.proc.submit_line("POLYGON");
    h.proc.submit_line("4");
    h.proc.submit_line("E");
    h.proc.submit_line("0,0");
    h.proc.submit_line("10,0");
    REQUIRE(h.cmds.size() == 1);
    const AddPolylineCommand& p = h.poly();
    REQUIRE(p.closed);
    REQUIRE(p.points.size() == 4);
    for (double s : side_lengths(p.points)) {
        REQUIRE(s == Approx(10.0));
    }
    // Both given endpoints are vertices of the result.
    const auto has = [&](Vec2 q) {
        return std::any_of(p.points.begin(), p.points.end(),
                           [&](const Vec2& v) { return length(v - q) < 1e-9; });
    };
    REQUIRE(has({0, 0}));
    REQUIRE(has({10, 0}));
    // Built to the LEFT of edge1->edge2, i.e. upwards here.
    double maxy = -1e9;
    for (const Vec2& v : p.points) {
        maxy = std::max(maxy, v.y);
    }
    REQUIRE(maxy == Approx(10.0));
}

TEST_CASE("#23: POLYGON refuses fewer than three sides and a zero radius") {
    ProcHarness h;
    h.proc.submit_line("POL");
    h.proc.submit_line("2"); // refused
    REQUIRE(h.cmds.empty());
    REQUIRE(h.proc.has_active_command()); // still asking for the side count
    h.proc.submit_line("4");
    h.proc.submit_line("0,0");
    h.proc.submit_line("I");
    h.proc.submit_line("0,0"); // zero radius -> refused
    REQUIRE(h.cmds.empty());
    REQUIRE(h.proc.has_active_command());
    h.proc.submit_line("5,0");
    REQUIRE(h.cmds.size() == 1);
}

TEST_CASE("#23: POLYGON defaults to four sides when the count is left blank") {
    ProcHarness h;
    h.proc.submit_line("POL");
    h.proc.submit_line(""); // Enter keeps the <4> default
    h.proc.submit_line("0,0");
    h.proc.submit_line("I");
    h.proc.submit_line("10,0");
    REQUIRE(h.cmds.size() == 1);
    REQUIRE(h.poly().points.size() == 4);
}

namespace {
struct PolyPromptOutput : musacad::command::CommandOutput {
    void append_line(const std::string& l) override { lines.push_back(l); }
    void set_prompt(const std::string& p) override { prompts.push_back(p); }
    std::vector<std::string> lines;
    std::vector<std::string> prompts;
};
struct PolyPromptHarness {
    std::vector<Command> cmds;
    PolyPromptOutput out;
    musacad::command::CommandProcessor proc{
        [this](Command c) { cmds.push_back(std::move(c)); }, nullptr, out};
};
const AddPolylineCommand* last_poly(const std::vector<Command>& cmds) {
    const AddPolylineCommand* found = nullptr;
    for (const auto& c : cmds) {
        if (const auto* p = std::get_if<AddPolylineCommand>(&c)) {
            found = p;
        }
    }
    return found;
}
} // namespace

TEST_CASE("#39: POLYGON remembers the side count and the fit, limits the sides, and stands a typed radius on a flat edge") {
    PolyPromptHarness h;
    h.proc.submit_line("POL");
    h.proc.submit_line("2000");
    REQUIRE(h.out.lines.back() == "Requires an integer between 3 and 1024.");
    h.proc.submit_line("6");
    h.proc.submit_line("0,0");
    h.proc.submit_line("C");
    h.proc.submit_line("10"); // typed: the bottom edge is horizontal
    const auto* hex = last_poly(h.cmds);
    REQUIRE(hex != nullptr);
    REQUIRE(hex->points.size() == 6);
    double min_y = 1e9;
    int at_min = 0;
    for (const Vec2& p : hex->points) {
        min_y = std::min(min_y, p.y);
    }
    for (const Vec2& p : hex->points) {
        if (std::abs(p.y - min_y) < 1e-9) {
            ++at_min;
        }
    }
    REQUIRE(at_min == 2); // two vertices share the lowest y: a flat bottom edge
    REQUIRE(min_y == Approx(-10.0)); // circumscribed: the apothem is the typed radius
    // The next POLYGON offers 6 and Circumscribed.
    PolyPromptHarness n;
    n.proc.submit_line("POL");
    REQUIRE(n.out.prompts.back() == "Enter number of sides <6>: ");
    n.proc.submit_line("");
    n.proc.submit_line("0,0");
    n.proc.submit_line(""); // keeps Circumscribed
    n.proc.submit_line("10,0");
    const auto* again = last_poly(n.cmds);
    REQUIRE(again != nullptr);
    REQUIRE(again->points.size() == 6);
    // Circumscribed about radius 10 pointing at (10, 0): a flat edge stands at x = 10,
    // its two vertices sharing that x.
    double max_x = -1e9;
    int at_max = 0;
    for (const Vec2& p : again->points) {
        max_x = std::max(max_x, p.x);
    }
    for (const Vec2& p : again->points) {
        if (std::abs(p.x - max_x) < 1e-9) {
            ++at_max;
        }
    }
    REQUIRE(max_x == Approx(10.0));
    REQUIRE(at_max == 2);
    // Edge mode previews the polygon on the edge; put the defaults back.
    PolyPromptHarness e;
    e.proc.submit_line("POL");
    e.proc.submit_line("4");
    e.proc.submit_line("E");
    e.proc.submit_line("0,0");
    REQUIRE(e.proc.preview().kind == musacad::command::PreviewKind::Polygon);
    REQUIRE(e.proc.preview().polygon_edge);
    e.proc.submit_line("10,0");
    const auto* sq = last_poly(e.cmds);
    REQUIRE(sq != nullptr);
    REQUIRE(sq->points.size() == 4);
    PolyPromptHarness r;
    r.proc.submit_line("POL");
    r.proc.submit_line("4");
    r.proc.submit_line("0,0");
    r.proc.submit_line("I");
    r.proc.cancel();
}
