// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (C) 2026 Kiran Pranay

#include "musacad/render/viewport_renderer.hpp"

#include "musacad/core/math/math.hpp"
#include "musacad/render/gpu/buffer.hpp"
#include "musacad/render/gpu/command_buffer.hpp"
#include "musacad/render/gpu/pipeline.hpp"
#include "musacad/render/grid.hpp"
#include "musacad/render/render_theme.hpp"
#include "musacad/render/stroke_font.hpp"

#include "musacad/render/embedded_shaders.hpp" // generated by the build

namespace musacad::render {

namespace {

// Colors / sizes are centralized in render_theme.hpp; these are local aliases so
// the call sites read cleanly.
constexpr ClearColor kBackground{0.09f, 0.10f, 0.12f, 1.0f};
constexpr const float (&kCrosshairColor)[4] = theme::kCrosshair;
constexpr const float (&kSnapColor)[4] = theme::kSnapMarker;
constexpr const float (&kSelectColor)[4] = theme::kSelected;
constexpr const float (&kHoverColor)[4] = theme::kHover;
constexpr const float (&kPreviewColor)[4] = theme::kPreview;
constexpr const float (&kGhostColor)[4] = theme::kGhost;
constexpr const float (&kGripColor)[4] = theme::kGrip;
constexpr const float (&kHotGripColor)[4] = theme::kHotGrip;
constexpr const float (&kWindowColor)[4] = theme::kWindow;
constexpr const float (&kCrossingColor)[4] = theme::kCrossing;
constexpr const float (&kGridMinor)[4] = theme::kGridMinor;
constexpr const float (&kGridMajor)[4] = theme::kGridMajor;
constexpr const float (&kSceneColor)[4] = theme::kScene;
constexpr const float (&kPointColor)[4] = theme::kPoint;
constexpr const float (&kOverlayColor)[4] = theme::kOverlay;

PipelineDesc make_line_pipeline_desc() {
    PipelineDesc d;
    d.vertex_src = shaders::line_vert;
    d.fragment_src = shaders::line_frag;
    d.attributes = {VertexAttribute{0, 0, 4, 0, 1}}; // vec4 per instance
    d.bindings = {VertexBinding{0, sizeof(float) * 4}};
    d.topology = Topology::Lines;
    return d;
}

PipelineDesc make_point_pipeline_desc() {
    PipelineDesc d;
    d.vertex_src = shaders::point_vert;
    d.fragment_src = shaders::point_frag;
    d.attributes = {VertexAttribute{0, 0, 2, 0, 1}}; // vec2 per instance
    d.bindings = {VertexBinding{0, sizeof(float) * 2}};
    d.topology = Topology::Points;
    return d;
}

// Thick scene lines: per-instance segment (vec4) expanded to a screen-space quad.
PipelineDesc make_thickline_pipeline_desc() {
    PipelineDesc d;
    d.vertex_src = shaders::thickline_vert;
    d.fragment_src = shaders::thickline_frag;
    d.attributes = {VertexAttribute{0, 0, 4, 0, 1}}; // vec4 per instance
    d.bindings = {VertexBinding{0, sizeof(float) * 4}};
    d.topology = Topology::TriangleStrip;
    return d;
}

// Filled triangles (arrowheads): per-vertex world position.
PipelineDesc make_fill_pipeline_desc() {
    PipelineDesc d;
    d.vertex_src = shaders::fill_vert;
    d.fragment_src = shaders::fill_frag;
    d.attributes = {VertexAttribute{0, 0, 2, 0, 0}}; // vec2 per vertex
    d.bindings = {VertexBinding{0, sizeof(float) * 2}};
    d.topology = Topology::Triangles;
    return d;
}

// AutoCAD-accurate fixed-screen lineweight: a weight in millimetres displays at a
// zoom-independent pixel thickness anchored to the real display density --
// px = mm * (DPI / 25.4) = mm * device_px_per_mm. The framebuffer is in physical
// device pixels, so the device-pixel-ratio is already folded into the DPI. The 1px
// floor is AutoCAD's "Default" hairline: a 0.25 mm line is ~0.95 px @96 DPI, i.e. a
// hairline, exactly as AutoCAD renders it. (zoom-independent: no camera scale here.)
float lineweight_px(std::uint8_t hundredths_mm, float device_px_per_mm) {
    return std::max(1.0f, (static_cast<float>(hundredths_mm) / 100.0f) * device_px_per_mm);
}

/// Converts world-space segment endpoint pairs (2 Vec2 per segment) into a flat
/// vec4-per-instance float buffer. Returns the instance count.
std::size_t pack_segments(const std::vector<core::Vec2>& endpoints, std::vector<float>& out) {
    const std::size_t segments = endpoints.size() / 2;
    out.clear();
    out.reserve(segments * 4);
    for (std::size_t i = 0; i < segments; ++i) {
        out.push_back(static_cast<float>(endpoints[2 * i].x));
        out.push_back(static_cast<float>(endpoints[2 * i].y));
        out.push_back(static_cast<float>(endpoints[2 * i + 1].x));
        out.push_back(static_cast<float>(endpoints[2 * i + 1].y));
    }
    return segments;
}

// Flatten a vec2 list to floats (for the fill pipeline: 1 position per vertex).
std::size_t pack_positions(const std::vector<core::Vec2>& pts, std::vector<float>& out) {
    out.clear();
    out.reserve(pts.size() * 2);
    for (const core::Vec2& p : pts) {
        out.push_back(static_cast<float>(p.x));
        out.push_back(static_cast<float>(p.y));
    }
    return pts.size();
}

core::Mat3 screen_to_ndc(int width, int height) {
    core::Mat3 m = core::Mat3::identity();
    m.m[0] = 2.0 / static_cast<double>(width);
    m.m[4] = -2.0 / static_cast<double>(height);
    m.m[6] = -1.0;
    m.m[7] = 1.0;
    return m;
}

void edge(std::vector<core::Vec2>& seg, core::Vec2 a, core::Vec2 b) {
    seg.push_back(a);
    seg.push_back(b);
}

/// Appends a snap-marker glyph (screen-space segments) centred at (cx,cy).
void append_marker(std::vector<core::Vec2>& seg, core::SnapType type, double cx, double cy,
                   double s) {
    using core::Vec2;
    switch (type) {
    case core::SnapType::Endpoint: // square
        edge(seg, {cx - s, cy - s}, {cx + s, cy - s});
        edge(seg, {cx + s, cy - s}, {cx + s, cy + s});
        edge(seg, {cx + s, cy + s}, {cx - s, cy + s});
        edge(seg, {cx - s, cy + s}, {cx - s, cy - s});
        break;
    case core::SnapType::Midpoint: // triangle
        edge(seg, {cx, cy - s}, {cx + s, cy + s});
        edge(seg, {cx + s, cy + s}, {cx - s, cy + s});
        edge(seg, {cx - s, cy + s}, {cx, cy - s});
        break;
    case core::SnapType::Center: { // octagon
        const int n = 8;
        for (int i = 0; i < n; ++i) {
            const double a0 = (static_cast<double>(i) / n) * core::kTwoPi;
            const double a1 = (static_cast<double>(i + 1) / n) * core::kTwoPi;
            edge(seg, {cx + s * std::cos(a0), cy + s * std::sin(a0)},
                 {cx + s * std::cos(a1), cy + s * std::sin(a1)});
        }
        break;
    }
    case core::SnapType::Intersection: // X
        edge(seg, {cx - s, cy - s}, {cx + s, cy + s});
        edge(seg, {cx - s, cy + s}, {cx + s, cy - s});
        break;
    case core::SnapType::Nearest: // bowtie
        edge(seg, {cx - s, cy - s}, {cx + s, cy - s});
        edge(seg, {cx - s, cy + s}, {cx + s, cy + s});
        edge(seg, {cx - s, cy - s}, {cx + s, cy + s});
        edge(seg, {cx + s, cy - s}, {cx - s, cy + s});
        break;
    case core::SnapType::Quadrant: // diamond
        edge(seg, {cx, cy - s}, {cx + s, cy});
        edge(seg, {cx + s, cy}, {cx, cy + s});
        edge(seg, {cx, cy + s}, {cx - s, cy});
        edge(seg, {cx - s, cy}, {cx, cy - s});
        break;
    case core::SnapType::Node: // square with an X
        edge(seg, {cx - s, cy - s}, {cx + s, cy - s});
        edge(seg, {cx + s, cy - s}, {cx + s, cy + s});
        edge(seg, {cx + s, cy + s}, {cx - s, cy + s});
        edge(seg, {cx - s, cy + s}, {cx - s, cy - s});
        edge(seg, {cx - s, cy - s}, {cx + s, cy + s});
        edge(seg, {cx - s, cy + s}, {cx + s, cy - s});
        break;
    case core::SnapType::Perpendicular: { // right-angle symbol
        edge(seg, {cx - s, cy - s}, {cx - s, cy + s}); // left
        edge(seg, {cx - s, cy + s}, {cx + s, cy + s}); // bottom
        const double q = s * 0.45;
        edge(seg, {cx - s, cy + q}, {cx - q, cy + q});
        edge(seg, {cx - q, cy + q}, {cx - q, cy + s});
        break;
    }
    case core::SnapType::Tangent: { // circle with a tangent line on top
        const int n = 8;
        for (int i = 0; i < n; ++i) {
            const double a0 = (static_cast<double>(i) / n) * core::kTwoPi;
            const double a1 = (static_cast<double>(i + 1) / n) * core::kTwoPi;
            edge(seg, {cx + s * std::cos(a0), cy + s * std::sin(a0)},
                 {cx + s * std::cos(a1), cy + s * std::sin(a1)});
        }
        edge(seg, {cx - s, cy - s}, {cx + s, cy - s});
        break;
    }
    case core::SnapType::Centroid: { // octagon with a plus
        const int n = 8;
        for (int i = 0; i < n; ++i) {
            const double a0 = (static_cast<double>(i) / n) * core::kTwoPi;
            const double a1 = (static_cast<double>(i + 1) / n) * core::kTwoPi;
            edge(seg, {cx + s * std::cos(a0), cy + s * std::sin(a0)},
                 {cx + s * std::cos(a1), cy + s * std::sin(a1)});
        }
        edge(seg, {cx, cy - s}, {cx, cy + s});
        edge(seg, {cx - s, cy}, {cx + s, cy});
        break;
    }
    case core::SnapType::None:
        break;
    }
}

} // namespace

ViewportRenderer::ViewportRenderer(GpuDevice& device) : device_(device) {
    line_pipeline_ = device_.create_pipeline(make_line_pipeline_desc());
    point_pipeline_ = device_.create_pipeline(make_point_pipeline_desc());
    thick_pipeline_ = device_.create_pipeline(make_thickline_pipeline_desc());
    fill_pipeline_ = device_.create_pipeline(make_fill_pipeline_desc());
    line_instances_ = device_.create_buffer(BufferUsage::Dynamic);
    point_instances_ = device_.create_buffer(BufferUsage::Dynamic);
    fill_buffer_ = device_.create_buffer(BufferUsage::Dynamic);
    grid_minor_ = device_.create_buffer(BufferUsage::Stream);
    grid_major_ = device_.create_buffer(BufferUsage::Stream);
    overlay_buffer_ = device_.create_buffer(BufferUsage::Stream);
    aux_buffer_ = device_.create_buffer(BufferUsage::Stream);
    cmd_ = device_.create_command_buffer();
}

void ViewportRenderer::upload_scene(const core::RenderSnapshot& snapshot) {
    line_count_ = pack_segments(snapshot.line_vertices, scratch_);
    line_instances_->upload(scratch_.data(), scratch_.size() * sizeof(float));
    const std::size_t line_bytes = scratch_.size() * sizeof(float);

    scratch_.clear();
    scratch_.reserve(snapshot.points.size() * 2);
    for (const core::Vec2& p : snapshot.points) {
        scratch_.push_back(static_cast<float>(p.x));
        scratch_.push_back(static_cast<float>(p.y));
    }
    point_count_ = snapshot.points.size();
    point_instances_->upload(scratch_.data(), scratch_.size() * sizeof(float));

    scratch_.clear();
    scratch_.reserve(snapshot.fill_vertices.size() * 2);
    for (const core::Vec2& p : snapshot.fill_vertices) {
        scratch_.push_back(static_cast<float>(p.x));
        scratch_.push_back(static_cast<float>(p.y));
    }
    fill_count_ = snapshot.fill_vertices.size();
    fill_buffer_->upload(scratch_.data(), scratch_.size() * sizeof(float));

    line_batches_ = snapshot.line_batches;
    point_batches_ = snapshot.point_batches;
    fill_batches_ = snapshot.fill_batches;

    uploaded_version_ = snapshot.geometry_version;
    stats_.scene_uploaded_bytes = line_bytes + scratch_.size() * sizeof(float);
}

void ViewportRenderer::render(GpuRenderTarget& target, const core::RenderSnapshot& snapshot,
                              const Camera2D& camera) {
    stats_ = RenderStats{};

    target.bind();
    cmd_->begin();
    cmd_->set_viewport(0, 0, target.width(), target.height());
    cmd_->clear(kBackground);

    // Scene geometry: re-upload only when the scene geometry changed (not on
    // cursor/selection/snap-only publishes).
    if (snapshot.geometry_version != uploaded_version_) {
        upload_scene(snapshot);
    }
    stats_.uploaded_version = uploaded_version_;
    stats_.line_instances = line_count_;
    stats_.point_instances = point_count_;

    const core::Mat3 view = camera.view_matrix();

    // Grid is screen-space-adaptive: regenerated each frame (cheap -- hundreds
    // of lines). This is independent of scene size.
    const GridResult g = build_grid(camera);
    const std::size_t minor_count = pack_segments(g.minor, scratch_);
    grid_minor_->upload(scratch_.data(), scratch_.size() * sizeof(float));
    std::size_t grid_bytes = scratch_.size() * sizeof(float);
    const std::size_t major_count = pack_segments(g.major, scratch_);
    grid_major_->upload(scratch_.data(), scratch_.size() * sizeof(float));
    grid_bytes += scratch_.size() * sizeof(float);
    stats_.grid_uploaded_bytes = grid_bytes;
    stats_.grid_lines = minor_count + major_count;

    // Lines + grid share the instanced-line pipeline.
    cmd_->bind_pipeline(*line_pipeline_);
    cmd_->set_uniform_mat3("u_transform", view);

    if (grid_visible_ && minor_count > 0) {
        cmd_->set_uniform_vec4("u_color", kGridMinor[0], kGridMinor[1], kGridMinor[2], kGridMinor[3]);
        cmd_->bind_vertex_buffer(0, *grid_minor_, 0);
        cmd_->draw_instanced(2, static_cast<std::uint32_t>(minor_count));
        ++stats_.draw_calls;
    }
    if (grid_visible_ && major_count > 0) {
        cmd_->set_uniform_vec4("u_color", kGridMajor[0], kGridMajor[1], kGridMajor[2], kGridMajor[3]);
        cmd_->bind_vertex_buffer(0, *grid_major_, 0);
        cmd_->draw_instanced(2, static_cast<std::uint32_t>(major_count));
        ++stats_.draw_calls;
    }
    // Scene lines: thick screen-space-expanded quads, one draw per (colour,
    // lineweight) batch. Width is in pixels (zoom-independent). LWDISPLAY off ->
    // a thin default for everything.
    if (line_count_ > 0) {
        cmd_->bind_pipeline(*thick_pipeline_);
        cmd_->set_uniform_mat3("u_transform", view);
        cmd_->set_uniform_vec2("u_viewport", static_cast<float>(target.width()),
                               static_cast<float>(target.height()));
        // HiDPI fix: the framebuffer is in physical pixels, so the effective
        // density is the logical px/mm times the device-pixel-ratio -- without this
        // every line is dpr x too thin on a HiDPI display.
        const float eff_px_per_mm = device_px_per_mm_ * device_pixel_ratio_;
        const auto draw_batch = [&](core::Rgb c, std::uint8_t lw, std::uint32_t first,
                                    std::uint32_t count) {
            const float w =
                snapshot.lineweight_display ? lineweight_px(lw, eff_px_per_mm) : device_pixel_ratio_;
            cmd_->set_uniform_float("u_halfwidth", w * 0.5f);
            cmd_->set_uniform_vec4("u_color", static_cast<float>(c.r) / 255.0f,
                                   static_cast<float>(c.g) / 255.0f, static_cast<float>(c.b) / 255.0f,
                                   1.0f);
            cmd_->bind_vertex_buffer(0, *line_instances_, first * sizeof(float) * 4);
            cmd_->draw_instanced(4, count); // 4-vertex triangle strip per segment
            ++stats_.draw_calls;
        };
        if (line_batches_.empty()) {
            draw_batch(core::Rgb{static_cast<std::uint8_t>(kSceneColor[0] * 255),
                                 static_cast<std::uint8_t>(kSceneColor[1] * 255),
                                 static_cast<std::uint8_t>(kSceneColor[2] * 255)},
                       25, 0, static_cast<std::uint32_t>(line_count_));
        } else {
            for (const core::ColorBatch& b : line_batches_) {
                draw_batch(b.color, b.lineweight, b.first, b.count);
            }
        }
    }

    // Filled arrowheads (and future hatching): one draw per colour batch.
    if (fill_count_ > 0 && !fill_batches_.empty()) {
        cmd_->bind_pipeline(*fill_pipeline_);
        cmd_->set_uniform_mat3("u_transform", view);
        for (const core::ColorBatch& b : fill_batches_) {
            cmd_->set_uniform_vec4("u_color", static_cast<float>(b.color.r) / 255.0f,
                                   static_cast<float>(b.color.g) / 255.0f,
                                   static_cast<float>(b.color.b) / 255.0f, 1.0f);
            cmd_->bind_vertex_buffer(0, *fill_buffer_, b.first * sizeof(float) * 2);
            cmd_->draw_instanced(b.count, 1); // b.count vertices, GL_TRIANGLES
            ++stats_.draw_calls;
        }
    }

    if (point_count_ > 0) {
        cmd_->bind_pipeline(*point_pipeline_);
        cmd_->set_uniform_mat3("u_transform", view);
        cmd_->set_uniform_float("u_point_size", 6.0f);
        if (point_batches_.empty()) {
            cmd_->set_uniform_vec4("u_color", kPointColor[0], kPointColor[1], kPointColor[2],
                                   kPointColor[3]);
            cmd_->bind_vertex_buffer(0, *point_instances_, 0);
            cmd_->draw_instanced(1, static_cast<std::uint32_t>(point_count_));
            ++stats_.draw_calls;
        } else {
            for (const core::ColorBatch& b : point_batches_) {
                cmd_->set_uniform_vec4("u_color", static_cast<float>(b.color.r) / 255.0f,
                                       static_cast<float>(b.color.g) / 255.0f,
                                       static_cast<float>(b.color.b) / 255.0f, 1.0f);
                cmd_->bind_vertex_buffer(0, *point_instances_, b.first * sizeof(float) * 2);
                cmd_->draw_instanced(1, b.count);
                ++stats_.draw_calls;
            }
        }
    }

    draw_selection_and_interaction(*cmd_, snapshot, view);
    draw_crosshair_and_snap(*cmd_, target.width(), target.height(), snapshot, camera);
    draw_overlay(*cmd_, target.width(), target.height());
    draw_dyn_labels(*cmd_, target.width(), target.height(), camera);
    draw_canvas_command(*cmd_, target.width(), target.height());

    cmd_->end();
    device_.submit(*cmd_);
}

void ViewportRenderer::draw_overlay(GpuCommandBuffer& cmd, int width, int height) {
    if (overlay_text_.empty()) {
        return;
    }
    std::vector<core::Vec2> segs;
    append_text_segments(overlay_text_, core::Vec2{12.0, 12.0}, 20.0, segs);
    const std::size_t count = pack_segments(segs, scratch_);
    if (count == 0) {
        return;
    }
    overlay_buffer_->upload(scratch_.data(), scratch_.size() * sizeof(float));

    // Screen-pixels (y-down) -> NDC (y-up).
    core::Mat3 screen = core::Mat3::identity();
    screen.m[0] = 2.0 / static_cast<double>(width);
    screen.m[4] = -2.0 / static_cast<double>(height);
    screen.m[6] = -1.0;
    screen.m[7] = 1.0;

    cmd.bind_pipeline(*line_pipeline_);
    cmd.set_uniform_mat3("u_transform", screen);
    cmd.set_uniform_vec4("u_color", kOverlayColor[0], kOverlayColor[1], kOverlayColor[2],
                         kOverlayColor[3]);
    cmd.bind_vertex_buffer(0, *overlay_buffer_, 0);
    cmd.draw_instanced(2, static_cast<std::uint32_t>(count));
    ++stats_.draw_calls;
}

void ViewportRenderer::draw_dyn_labels(GpuCommandBuffer& cmd, int width, int height,
                                       const Camera2D& camera) {
    if (overlay_.dyn_labels.empty()) {
        return;
    }
    const double dpr = static_cast<double>(device_pixel_ratio_);
    const double h = 15.0 * dpr;       // glyph height (device px)
    const double pad = 6.0 * dpr;      // box padding
    const double caret_gap = 3.0 * dpr;

    std::vector<core::Vec2> fills;     // box backgrounds (triangles: 6 verts/box)
    std::vector<core::Vec2> lines;     // unfocused borders + ALL text + caret
    std::vector<core::Vec2> focus;     // focused box border (brighter)

    for (const DynLabel& label : overlay_.dyn_labels) {
        const core::Vec2 s = camera.world_to_screen(label.anchor); // device px
        std::vector<core::Vec2> txt;
        const double tw = append_text_segments(label.text, {0.0, 0.0}, h, txt);
        const double bw = tw + 2.0 * pad + (label.focused ? caret_gap + 2.0 * dpr : 0.0);
        const double bh = h + 2.0 * pad;
        // Nudge the box OUTWARD from the geometry (along the projected `out` dir) so it
        // sits just outside the edge and the fields never overlap each other.
        core::Vec2 c = s;
        if (label.out.x != 0.0 || label.out.y != 0.0) {
            const core::Vec2 o = camera.world_to_screen(label.anchor + label.out);
            const core::Vec2 d = o - s;
            const double len = core::length(d);
            if (len > 1e-6) {
                const core::Vec2 dir{d.x / len, d.y / len};
                const double push =
                    0.5 * (std::abs(dir.x) * bw + std::abs(dir.y) * bh) + 8.0 * dpr;
                c = {s.x + dir.x * push, s.y + dir.y * push};
            }
        }
        const double bx = c.x - bw * 0.5;
        const double by = c.y - bh * 0.5;

        // Filled dark background (two triangles).
        fills.push_back({bx, by});
        fills.push_back({bx + bw, by});
        fills.push_back({bx + bw, by + bh});
        fills.push_back({bx, by});
        fills.push_back({bx + bw, by + bh});
        fills.push_back({bx, by + bh});

        // Border (brighter when focused).
        std::vector<core::Vec2>& border = label.focused ? focus : lines;
        edge(border, {bx, by}, {bx + bw, by});
        edge(border, {bx + bw, by}, {bx + bw, by + bh});
        edge(border, {bx + bw, by + bh}, {bx, by + bh});
        edge(border, {bx, by + bh}, {bx, by});

        // The number text.
        append_text_segments(label.text, {bx + pad, by + pad}, h, lines);

        // Text caret on the active field.
        if (label.focused) {
            const double cx = bx + pad + tw + caret_gap;
            edge(lines, {cx, by + pad}, {cx, by + pad + h});
        }
    }

    const core::Mat3 screen = screen_to_ndc(width, height);

    if (!fills.empty()) {
        const std::size_t n = pack_positions(fills, scratch_);
        aux_buffer_->upload(scratch_.data(), scratch_.size() * sizeof(float));
        cmd.bind_pipeline(*fill_pipeline_);
        cmd.set_uniform_mat3("u_transform", screen);
        cmd.set_uniform_vec4("u_color", 0.16f, 0.17f, 0.20f, 0.96f); // visible dark box fill
        cmd.bind_vertex_buffer(0, *aux_buffer_, 0);
        cmd.draw_instanced(static_cast<std::uint32_t>(n), 1);
        ++stats_.draw_calls;
    }

    cmd.bind_pipeline(*line_pipeline_);
    cmd.set_uniform_mat3("u_transform", screen);
    if (!lines.empty()) {
        const std::size_t n = pack_segments(lines, scratch_);
        overlay_buffer_->upload(scratch_.data(), scratch_.size() * sizeof(float));
        cmd.set_uniform_vec4("u_color", kOverlayColor[0], kOverlayColor[1], kOverlayColor[2],
                             kOverlayColor[3]);
        cmd.bind_vertex_buffer(0, *overlay_buffer_, 0);
        cmd.draw_instanced(2, static_cast<std::uint32_t>(n));
        ++stats_.draw_calls;
    }
    if (!focus.empty()) {
        const std::size_t n = pack_segments(focus, scratch_);
        overlay_buffer_->upload(scratch_.data(), scratch_.size() * sizeof(float));
        cmd.set_uniform_vec4("u_color", 0.48f, 0.78f, 1.0f, 1.0f); // active-field highlight
        cmd.bind_vertex_buffer(0, *overlay_buffer_, 0);
        cmd.draw_instanced(2, static_cast<std::uint32_t>(n));
        ++stats_.draw_calls;
    }
}

void ViewportRenderer::draw_canvas_command(GpuCommandBuffer& cmd, int width, int height) {
    const CanvasCommandUI& ui = overlay_.command_ui;
    if (!ui.active) {
        return;
    }
    const core::Mat3 screen = screen_to_ndc(width, height);
    const auto fill = [&](const std::vector<core::Vec2>& tris, float r, float g, float b, float a) {
        if (tris.empty()) {
            return;
        }
        const std::size_t n = pack_positions(tris, scratch_);
        aux_buffer_->upload(scratch_.data(), scratch_.size() * sizeof(float));
        cmd.bind_pipeline(*fill_pipeline_);
        cmd.set_uniform_mat3("u_transform", screen);
        cmd.set_uniform_vec4("u_color", r, g, b, a);
        cmd.bind_vertex_buffer(0, *aux_buffer_, 0);
        cmd.draw_instanced(static_cast<std::uint32_t>(n), 1);
        ++stats_.draw_calls;
    };
    fill(ui.box_fills, 0.12f, 0.13f, 0.16f, 0.96f);   // panel / cells (dark)
    fill(ui.hi_fills, 0.18f, 0.34f, 0.52f, 0.96f);    // highlighted suggestion row
    fill(ui.glyph_fills, 0.90f, 0.92f, 0.95f, 1.0f);  // TTF text (one batch, all rows)
    if (!ui.lines.empty()) {
        const std::size_t n = pack_segments(ui.lines, scratch_);
        overlay_buffer_->upload(scratch_.data(), scratch_.size() * sizeof(float));
        cmd.bind_pipeline(*line_pipeline_);
        cmd.set_uniform_mat3("u_transform", screen);
        cmd.set_uniform_vec4("u_color", 0.40f, 0.55f, 0.75f, 1.0f); // borders + caret
        cmd.bind_vertex_buffer(0, *overlay_buffer_, 0);
        cmd.draw_instanced(2, static_cast<std::uint32_t>(n));
        ++stats_.draw_calls;
    }
}

void ViewportRenderer::draw_selection_and_interaction(GpuCommandBuffer& cmd,
                                                      const core::RenderSnapshot& snapshot,
                                                      const core::Mat3& view) {
    cmd.bind_pipeline(*line_pipeline_);
    cmd.set_uniform_mat3("u_transform", view);

    const auto draw_world = [&](const std::vector<core::Vec2>& seg, const float (&color)[4]) {
        const std::size_t n = pack_segments(seg, scratch_);
        if (n == 0) {
            return;
        }
        aux_buffer_->upload(scratch_.data(), scratch_.size() * sizeof(float));
        cmd.set_uniform_vec4("u_color", color[0], color[1], color[2], color[3]);
        cmd.bind_vertex_buffer(0, *aux_buffer_, 0);
        cmd.draw_instanced(2, static_cast<std::uint32_t>(n));
        ++stats_.draw_calls;
    };

    // Rollover (hover) highlight -- the entity under the cursor, drawn beneath
    // the selection highlight so a selected entity still reads as selected.
    if (!snapshot.hover_line_vertices.empty()) {
        draw_world(snapshot.hover_line_vertices, kHoverColor);
    }

    // Selected geometry highlight.
    if (!snapshot.selected_line_vertices.empty()) {
        draw_world(snapshot.selected_line_vertices, kSelectColor);
    }

    // Ghost: transform the selected geometry render-side (move/mirror/rotate/scale).
    if (overlay_.ghost_mode != 0 && !snapshot.selected_line_vertices.empty()) {
        std::vector<core::Vec2> ghost;
        ghost.reserve(snapshot.selected_line_vertices.size());
        const auto& src = snapshot.selected_line_vertices;
        if (overlay_.ghost_mode == 1) { // move
            const core::Vec2 d = overlay_.ghost_b - overlay_.ghost_a;
            for (const core::Vec2& v : src) {
                ghost.push_back(v + d);
            }
        } else if (overlay_.ghost_mode == 2) { // mirror across ghost_a..ghost_b
            const core::Vec2 dir = core::normalized(overlay_.ghost_b - overlay_.ghost_a);
            for (const core::Vec2& v : src) {
                const core::Vec2 ap = v - overlay_.ghost_a;
                const double t = core::dot(ap, dir);
                const core::Vec2 proj = overlay_.ghost_a + dir * t;
                ghost.push_back(proj * 2.0 - v);
            }
        } else if (overlay_.ghost_mode == 3) { // rotate about ghost_a
            const double cs = std::cos(overlay_.ghost_param);
            const double sn = std::sin(overlay_.ghost_param);
            for (const core::Vec2& v : src) {
                const core::Vec2 d = v - overlay_.ghost_a;
                ghost.push_back({overlay_.ghost_a.x + d.x * cs - d.y * sn,
                                 overlay_.ghost_a.y + d.x * sn + d.y * cs});
            }
        } else { // scale about ghost_a
            const double f = overlay_.ghost_param;
            for (const core::Vec2& v : src) {
                ghost.push_back(overlay_.ghost_a + (v - overlay_.ghost_a) * f);
            }
        }
        draw_world(ghost, kGhostColor);
    }

    // Live command preview (rubber-band).
    if (!overlay_.preview_segments.empty()) {
        draw_world(overlay_.preview_segments, kPreviewColor);
    }

    // Selection rubber-band rectangle.
    if (overlay_.rect_mode != 0) {
        const core::Vec2 a = overlay_.rect_a;
        const core::Vec2 b = overlay_.rect_b;
        std::vector<core::Vec2> rect;
        edge(rect, {a.x, a.y}, {b.x, a.y});
        edge(rect, {b.x, a.y}, {b.x, b.y});
        edge(rect, {b.x, b.y}, {a.x, b.y});
        edge(rect, {a.x, b.y}, {a.x, a.y});
        draw_world(rect, overlay_.rect_mode == 2 ? kCrossingColor : kWindowColor);
    }

    // Grip drag preview: the edited entity (computed geometry-side on a temp store)
    // drawn in the hot colour. Lines through the line pipeline; arrowhead fills
    // through the fill pipeline (rebound after, since draw_world expects the line
    // pipeline -- this is the last line draw so order is fine).
    if (!snapshot.grip_preview_segments.empty()) {
        draw_world(snapshot.grip_preview_segments, kHotGripColor);
    }
    if (!snapshot.grip_preview_fills.empty()) {
        const std::size_t n = pack_positions(snapshot.grip_preview_fills, scratch_);
        if (n > 0) {
            cmd.bind_pipeline(*fill_pipeline_);
            cmd.set_uniform_mat3("u_transform", view);
            fill_buffer_->upload(scratch_.data(), scratch_.size() * sizeof(float));
            cmd.set_uniform_vec4("u_color", kHotGripColor[0], kHotGripColor[1], kHotGripColor[2],
                                 kHotGripColor[3]);
            cmd.bind_vertex_buffer(0, *fill_buffer_, 0);
            cmd.draw_instanced(static_cast<std::uint32_t>(n), 1);
            ++stats_.draw_calls;
        }
    }
}

void ViewportRenderer::draw_crosshair_and_snap(GpuCommandBuffer& cmd, int width, int height,
                                               const core::RenderSnapshot& snapshot,
                                               const Camera2D& camera) {
    const core::Mat3 screen = screen_to_ndc(width, height);
    cmd.bind_pipeline(*line_pipeline_);
    cmd.set_uniform_mat3("u_transform", screen);

    // AutoCAD-style cursor: full-screen crosshair + a center pick-box. Pure
    // render-side, from the raw cursor -> always smooth, no geometry round-trip.
    if (cursor_visible_) {
        // Pick-box at a constant *physical* size: scale by DPR so it isn't tiny on
        // a HiDPI framebuffer.
        const double kPickBoxHalfPx = 6.0 * device_pixel_ratio_;
        const double cx = static_cast<double>(cursor_x_);
        const double cy = static_cast<double>(cursor_y_);
        std::vector<core::Vec2> seg;
        edge(seg, {0.0, cy}, {static_cast<double>(width), cy});  // horizontal
        edge(seg, {cx, 0.0}, {cx, static_cast<double>(height)}); // vertical
        // Center pick-box (square).
        const double h = kPickBoxHalfPx;
        edge(seg, {cx - h, cy - h}, {cx + h, cy - h});
        edge(seg, {cx + h, cy - h}, {cx + h, cy + h});
        edge(seg, {cx + h, cy + h}, {cx - h, cy + h});
        edge(seg, {cx - h, cy + h}, {cx - h, cy - h});
        const std::size_t n = pack_segments(seg, scratch_);
        aux_buffer_->upload(scratch_.data(), scratch_.size() * sizeof(float));
        cmd.set_uniform_vec4("u_color", kCrosshairColor[0], kCrosshairColor[1], kCrosshairColor[2],
                             kCrosshairColor[3]);
        cmd.bind_vertex_buffer(0, *aux_buffer_, 0);
        cmd.draw_instanced(2, static_cast<std::uint32_t>(n));
        ++stats_.draw_calls;
    }

    // Snap marker: from the snapshot (computed geometry-side), drawn in screen
    // space at a constant pixel size.
    if (snapshot.has_snap) {
        const core::Vec2 sp = camera.world_to_screen(snapshot.snap_point);
        std::vector<core::Vec2> base;
        // Constant physical size: scale by DPR (HiDPI-consistent).
        append_marker(base, snapshot.snap_type, sp.x, sp.y,
                      theme::kSnapMarkerHalfPx * device_pixel_ratio_);
        // Fake a bold stroke by overdrawing the glyph at small offsets (core-GL
        // line width is unreliable). Keeps it one draw call.
        const double o = theme::kMarkerStrokePx * device_pixel_ratio_;
        std::vector<core::Vec2> seg;
        seg.reserve(base.size() * 4);
        for (const core::Vec2 off : {core::Vec2{0, 0}, core::Vec2{o, 0}, core::Vec2{0, o},
                                     core::Vec2{o, o}}) {
            for (const core::Vec2& p : base) {
                seg.push_back(p + off);
            }
        }
        const std::size_t n = pack_segments(seg, scratch_);
        if (n > 0) {
            aux_buffer_->upload(scratch_.data(), scratch_.size() * sizeof(float));
            cmd.set_uniform_vec4("u_color", kSnapColor[0], kSnapColor[1], kSnapColor[2],
                                 kSnapColor[3]);
            cmd.bind_vertex_buffer(0, *aux_buffer_, 0);
            cmd.draw_instanced(2, static_cast<std::uint32_t>(n));
            ++stats_.draw_calls;
        }
    }

    // Grips of the selected set: small filled squares at a constant pixel size, the
    // grabbed/hovered one in the hot colour. Batched: at most two fill draws.
    if (!snapshot.grips.empty()) {
        const double hpx = theme::kGripHalfPx * device_pixel_ratio_; // physical-consistent
        std::vector<core::Vec2> normal;
        std::vector<core::Vec2> hot;
        for (std::size_t i = 0; i < snapshot.grips.size(); ++i) {
            const core::Vec2 s = camera.world_to_screen(snapshot.grips[i].pos);
            std::vector<core::Vec2>& dst =
                (static_cast<int>(i) == snapshot.hot_grip) ? hot : normal;
            const core::Vec2 a{s.x - hpx, s.y - hpx};
            const core::Vec2 b{s.x + hpx, s.y - hpx};
            const core::Vec2 c{s.x + hpx, s.y + hpx};
            const core::Vec2 d{s.x - hpx, s.y + hpx};
            dst.push_back(a);
            dst.push_back(b);
            dst.push_back(c);
            dst.push_back(a);
            dst.push_back(c);
            dst.push_back(d);
        }
        cmd.bind_pipeline(*fill_pipeline_);
        cmd.set_uniform_mat3("u_transform", screen);
        const auto draw_squares = [&](const std::vector<core::Vec2>& tris, const float (&col)[4]) {
            const std::size_t n = pack_positions(tris, scratch_);
            if (n == 0) {
                return;
            }
            fill_buffer_->upload(scratch_.data(), scratch_.size() * sizeof(float));
            cmd.set_uniform_vec4("u_color", col[0], col[1], col[2], col[3]);
            cmd.bind_vertex_buffer(0, *fill_buffer_, 0);
            cmd.draw_instanced(static_cast<std::uint32_t>(n), 1);
            ++stats_.draw_calls;
        };
        draw_squares(normal, kGripColor);
        draw_squares(hot, kHotGripColor);
    }
}

} // namespace musacad::render
