// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (C) 2026 Pranay Kiran

#include "musacad/render/viewport_renderer.hpp"

#include <algorithm>
#include <iterator>
#include <vector>

#include "musacad/core/math/math.hpp"
#include "musacad/render/gpu/buffer.hpp"
#include "musacad/render/gpu/command_buffer.hpp"
#include "musacad/render/gpu/pipeline.hpp"
#include "musacad/render/grid.hpp"
#include "musacad/render/render_theme.hpp"
#include "musacad/render/stroke_font.hpp"

#include "musacad/core/image.hpp"
#include "musacad/render/embedded_shaders.hpp" // generated by the build

namespace musacad::render {

namespace {

// Colors / sizes are centralized in render_theme.hpp; these are local aliases so
// the call sites read cleanly.
constexpr ClearColor kBackground{0.09f, 0.10f, 0.12f, 1.0f};
constexpr const float (&kCrosshairColor)[4] = theme::kCrosshair;
constexpr const float (&kSnapColor)[4] = theme::kSnapMarker;
constexpr const float (&kSelectColor)[4] = theme::kSelected;
constexpr const float (&kHoverColor)[4] = theme::kHover;
constexpr const float (&kPreviewColor)[4] = theme::kPreview;
constexpr const float (&kGhostColor)[4] = theme::kGhost;
constexpr const float (&kGripColor)[4] = theme::kGrip;
constexpr const float (&kHotGripColor)[4] = theme::kHotGrip;
constexpr const float (&kWindowColor)[4] = theme::kWindow;
constexpr const float (&kCrossingColor)[4] = theme::kCrossing;
constexpr const float (&kGridMinor)[4] = theme::kGridMinor;
constexpr const float (&kGridMajor)[4] = theme::kGridMajor;
constexpr const float (&kSceneColor)[4] = theme::kScene;
constexpr const float (&kPointColor)[4] = theme::kPoint;
constexpr const float (&kOverlayColor)[4] = theme::kOverlay;

PipelineDesc make_line_pipeline_desc() {
    PipelineDesc d;
    d.vertex_src = shaders::line_vert;
    d.fragment_src = shaders::line_frag;
    d.attributes = {VertexAttribute{0, 0, 4, 0, 1}}; // vec4 per instance
    d.bindings = {VertexBinding{0, sizeof(float) * 4}};
    d.topology = Topology::Lines;
    return d;
}

PipelineDesc make_point_pipeline_desc() {
    PipelineDesc d;
    d.vertex_src = shaders::point_vert;
    d.fragment_src = shaders::point_frag;
    d.attributes = {VertexAttribute{0, 0, 2, 0, 1}}; // vec2 per instance
    d.bindings = {VertexBinding{0, sizeof(float) * 2}};
    d.topology = Topology::Points;
    return d;
}

// Thick scene lines: per-instance segment (vec4) expanded to a screen-space quad.
PipelineDesc make_thickline_pipeline_desc() {
    PipelineDesc d;
    d.vertex_src = shaders::thickline_vert;
    d.fragment_src = shaders::thickline_frag;
    d.attributes = {VertexAttribute{0, 0, 4, 0, 1}}; // vec4 per instance
    d.bindings = {VertexBinding{0, sizeof(float) * 4}};
    d.topology = Topology::TriangleStrip;
    return d;
}

// Filled triangles (arrowheads): per-vertex world position.
PipelineDesc make_image_pipeline_desc() {
    PipelineDesc d;
    d.vertex_src = shaders::image_vert;
    d.fragment_src = shaders::image_frag;
    d.attributes = {VertexAttribute{0, 0, 2, 0, 0},                   // vec2 position
                    VertexAttribute{1, 0, 2, sizeof(float) * 2, 0}};  // vec2 uv
    d.bindings = {VertexBinding{0, sizeof(float) * 4}};
    d.topology = Topology::Triangles;
    return d;
}

PipelineDesc make_fill_pipeline_desc() {
    PipelineDesc d;
    d.vertex_src = shaders::fill_vert;
    d.fragment_src = shaders::fill_frag;
    d.attributes = {VertexAttribute{0, 0, 2, 0, 0}}; // vec2 per vertex
    d.bindings = {VertexBinding{0, sizeof(float) * 2}};
    d.topology = Topology::Triangles;
    return d;
}

// AutoCAD-accurate fixed-screen lineweight: a weight in millimetres displays at a
// zoom-independent pixel thickness anchored to the real display density --
// px = mm * (DPI / 25.4) = mm * device_px_per_mm. The framebuffer is in physical
// device pixels, so the device-pixel-ratio is already folded into the DPI. The 1px
// floor is AutoCAD's "Default" hairline: a 0.25 mm line is ~0.95 px @96 DPI, i.e. a
// hairline, exactly as AutoCAD renders it. (zoom-independent: no camera scale here.)
float lineweight_px(std::uint8_t hundredths_mm, float device_px_per_mm) {
    return std::max(1.0f, (static_cast<float>(hundredths_mm) / 100.0f) * device_px_per_mm);
}

// On-screen weight for single-stroke TEXT (hundredths mm). Text carries no real
// lineweight (0 -> a 1px hairline that reads as "dull" at typical zoom on a dark
// background). Rendering stroke text at a ~0.5 mm-equivalent fattens the glyphs so they
// look professional and present while staying single-stroke (engineering convention).
// SCREEN ONLY: the PLOT path honours the entity's actual 0 weight, so paper ink is
// unchanged. Empirical, screenshot-tuned; not a user/entity property.
constexpr std::uint8_t kTextScreenWeightHmm = 50;

// The text weight above is the CAP. For small text it is capped further to this fraction of
// the glyph's ON-SCREEN height, so tiny title-block fields read crisp instead of blocky while
// title-size text keeps the full ~0.5 mm presence (the cap only binds below ~glyph height /
// frac). Floored at a 1px hairline so text never disappears.
constexpr float kTextStrokeFrac = 0.12f;

/// Converts world-space segment endpoint pairs (2 Vec2 per segment) into a flat
/// vec4-per-instance float buffer. Returns the instance count.
std::size_t pack_segments(const std::vector<core::Vec2>& endpoints, std::vector<float>& out) {
    const std::size_t segments = endpoints.size() / 2;
    out.clear();
    out.reserve(segments * 4);
    for (std::size_t i = 0; i < segments; ++i) {
        out.push_back(static_cast<float>(endpoints[2 * i].x));
        out.push_back(static_cast<float>(endpoints[2 * i].y));
        out.push_back(static_cast<float>(endpoints[2 * i + 1].x));
        out.push_back(static_cast<float>(endpoints[2 * i + 1].y));
    }
    return segments;
}

// Flatten a vec2 list to floats (for the fill pipeline: 1 position per vertex).
std::size_t pack_positions(const std::vector<core::Vec2>& pts, std::vector<float>& out) {
    out.clear();
    out.reserve(pts.size() * 2);
    for (const core::Vec2& p : pts) {
        out.push_back(static_cast<float>(p.x));
        out.push_back(static_cast<float>(p.y));
    }
    return pts.size();
}

core::Mat3 screen_to_ndc(int width, int height) {
    core::Mat3 m = core::Mat3::identity();
    m.m[0] = 2.0 / static_cast<double>(width);
    m.m[4] = -2.0 / static_cast<double>(height);
    m.m[6] = -1.0;
    m.m[7] = 1.0;
    return m;
}

void edge(std::vector<core::Vec2>& seg, core::Vec2 a, core::Vec2 b) {
    seg.push_back(a);
    seg.push_back(b);
}

/// Appends a snap-marker glyph (screen-space segments) centred at (cx,cy).
void append_marker(std::vector<core::Vec2>& seg, core::SnapType type, double cx, double cy,
                   double s) {
    using core::Vec2;
    switch (type) {
    case core::SnapType::Endpoint: // square
        edge(seg, {cx - s, cy - s}, {cx + s, cy - s});
        edge(seg, {cx + s, cy - s}, {cx + s, cy + s});
        edge(seg, {cx + s, cy + s}, {cx - s, cy + s});
        edge(seg, {cx - s, cy + s}, {cx - s, cy - s});
        break;
    case core::SnapType::Midpoint: // triangle
        edge(seg, {cx, cy - s}, {cx + s, cy + s});
        edge(seg, {cx + s, cy + s}, {cx - s, cy + s});
        edge(seg, {cx - s, cy + s}, {cx, cy - s});
        break;
    case core::SnapType::Center: { // octagon
        const int n = 8;
        for (int i = 0; i < n; ++i) {
            const double a0 = (static_cast<double>(i) / n) * core::kTwoPi;
            const double a1 = (static_cast<double>(i + 1) / n) * core::kTwoPi;
            edge(seg, {cx + s * std::cos(a0), cy + s * std::sin(a0)},
                 {cx + s * std::cos(a1), cy + s * std::sin(a1)});
        }
        break;
    }
    case core::SnapType::Intersection: // X
        edge(seg, {cx - s, cy - s}, {cx + s, cy + s});
        edge(seg, {cx - s, cy + s}, {cx + s, cy - s});
        break;
    case core::SnapType::Nearest: // bowtie
        edge(seg, {cx - s, cy - s}, {cx + s, cy - s});
        edge(seg, {cx - s, cy + s}, {cx + s, cy + s});
        edge(seg, {cx - s, cy - s}, {cx + s, cy + s});
        edge(seg, {cx + s, cy - s}, {cx - s, cy + s});
        break;
    case core::SnapType::Quadrant: // diamond
        edge(seg, {cx, cy - s}, {cx + s, cy});
        edge(seg, {cx + s, cy}, {cx, cy + s});
        edge(seg, {cx, cy + s}, {cx - s, cy});
        edge(seg, {cx - s, cy}, {cx, cy - s});
        break;
    case core::SnapType::Node: // square with an X
        edge(seg, {cx - s, cy - s}, {cx + s, cy - s});
        edge(seg, {cx + s, cy - s}, {cx + s, cy + s});
        edge(seg, {cx + s, cy + s}, {cx - s, cy + s});
        edge(seg, {cx - s, cy + s}, {cx - s, cy - s});
        edge(seg, {cx - s, cy - s}, {cx + s, cy + s});
        edge(seg, {cx - s, cy + s}, {cx + s, cy - s});
        break;
    case core::SnapType::Perpendicular: { // right-angle symbol
        edge(seg, {cx - s, cy - s}, {cx - s, cy + s}); // left
        edge(seg, {cx - s, cy + s}, {cx + s, cy + s}); // bottom
        const double q = s * 0.45;
        edge(seg, {cx - s, cy + q}, {cx - q, cy + q});
        edge(seg, {cx - q, cy + q}, {cx - q, cy + s});
        break;
    }
    case core::SnapType::Tangent: { // circle with a tangent line on top
        const int n = 8;
        for (int i = 0; i < n; ++i) {
            const double a0 = (static_cast<double>(i) / n) * core::kTwoPi;
            const double a1 = (static_cast<double>(i + 1) / n) * core::kTwoPi;
            edge(seg, {cx + s * std::cos(a0), cy + s * std::sin(a0)},
                 {cx + s * std::cos(a1), cy + s * std::sin(a1)});
        }
        edge(seg, {cx - s, cy - s}, {cx + s, cy - s});
        break;
    }
    case core::SnapType::Centroid: { // octagon with a plus
        const int n = 8;
        for (int i = 0; i < n; ++i) {
            const double a0 = (static_cast<double>(i) / n) * core::kTwoPi;
            const double a1 = (static_cast<double>(i + 1) / n) * core::kTwoPi;
            edge(seg, {cx + s * std::cos(a0), cy + s * std::sin(a0)},
                 {cx + s * std::cos(a1), cy + s * std::sin(a1)});
        }
        edge(seg, {cx, cy - s}, {cx, cy + s});
        edge(seg, {cx - s, cy}, {cx + s, cy});
        break;
    }
    case core::SnapType::Insertion: { // two overlapping squares
        const double q = s * 0.55;
        edge(seg, {cx - s, cy - q}, {cx + q, cy - q});
        edge(seg, {cx + q, cy - q}, {cx + q, cy + s});
        edge(seg, {cx + q, cy + s}, {cx - s, cy + s});
        edge(seg, {cx - s, cy + s}, {cx - s, cy - q});
        edge(seg, {cx - q, cy - s}, {cx + s, cy - s});
        edge(seg, {cx + s, cy - s}, {cx + s, cy + q});
        edge(seg, {cx + s, cy + q}, {cx - q, cy + q});
        edge(seg, {cx - q, cy + q}, {cx - q, cy - s});
        break;
    }
    case core::SnapType::ApparentIntersection: // X inside a square
        edge(seg, {cx - s, cy - s}, {cx + s, cy - s});
        edge(seg, {cx + s, cy - s}, {cx + s, cy + s});
        edge(seg, {cx + s, cy + s}, {cx - s, cy + s});
        edge(seg, {cx - s, cy + s}, {cx - s, cy - s});
        edge(seg, {cx - s * 0.6, cy - s * 0.6}, {cx + s * 0.6, cy + s * 0.6});
        edge(seg, {cx - s * 0.6, cy + s * 0.6}, {cx + s * 0.6, cy - s * 0.6});
        break;
    case core::SnapType::Parallel: // two parallel diagonals
        edge(seg, {cx - s, cy + s * 0.4}, {cx + s * 0.4, cy - s});
        edge(seg, {cx - s * 0.4, cy + s}, {cx + s, cy - s * 0.4});
        break;
    case core::SnapType::None:
        break;
    }
}

} // namespace

ViewportRenderer::ViewportRenderer(GpuDevice& device) : device_(device) {
    line_pipeline_ = device_.create_pipeline(make_line_pipeline_desc());
    point_pipeline_ = device_.create_pipeline(make_point_pipeline_desc());
    thick_pipeline_ = device_.create_pipeline(make_thickline_pipeline_desc());
    fill_pipeline_ = device_.create_pipeline(make_fill_pipeline_desc());
    image_pipeline_ = device_.create_pipeline(make_image_pipeline_desc());
    image_buffer_ = device_.create_buffer(BufferUsage::Stream);
    line_instances_ = device_.create_buffer(BufferUsage::Dynamic);
    point_instances_ = device_.create_buffer(BufferUsage::Dynamic);
    fill_buffer_ = device_.create_buffer(BufferUsage::Dynamic);
    wipeout_buffer_ = device_.create_buffer(BufferUsage::Dynamic);
    grid_minor_ = device_.create_buffer(BufferUsage::Stream);
    grid_major_ = device_.create_buffer(BufferUsage::Stream);
    overlay_buffer_ = device_.create_buffer(BufferUsage::Stream);
    aux_buffer_ = device_.create_buffer(BufferUsage::Stream);
    cmd_ = device_.create_command_buffer();
}

void ViewportRenderer::upload_scene(const core::RenderSnapshot& snapshot) {
    line_count_ = pack_segments(snapshot.line_vertices, scratch_);
    line_instances_->upload(scratch_.data(), scratch_.size() * sizeof(float));
    const std::size_t line_bytes = scratch_.size() * sizeof(float);

    scratch_.clear();
    scratch_.reserve(snapshot.points.size() * 2);
    for (const core::Vec2& p : snapshot.points) {
        scratch_.push_back(static_cast<float>(p.x));
        scratch_.push_back(static_cast<float>(p.y));
    }
    point_count_ = snapshot.points.size();
    point_instances_->upload(scratch_.data(), scratch_.size() * sizeof(float));

    scratch_.clear();
    scratch_.reserve(snapshot.fill_vertices.size() * 2);
    for (const core::Vec2& p : snapshot.fill_vertices) {
        scratch_.push_back(static_cast<float>(p.x));
        scratch_.push_back(static_cast<float>(p.y));
    }
    fill_count_ = snapshot.fill_vertices.size();
    fill_buffer_->upload(scratch_.data(), scratch_.size() * sizeof(float));

    scratch_.clear();
    scratch_.reserve(snapshot.wipeout_vertices.size() * 2);
    for (const core::Vec2& p : snapshot.wipeout_vertices) {
        scratch_.push_back(static_cast<float>(p.x));
        scratch_.push_back(static_cast<float>(p.y));
    }
    wipeout_count_ = snapshot.wipeout_vertices.size();
    if (wipeout_count_ > 0) {
        wipeout_buffer_->upload(scratch_.data(), scratch_.size() * sizeof(float));
    }

    line_batches_ = snapshot.line_batches;
    point_batches_ = snapshot.point_batches;
    fill_batches_ = snapshot.fill_batches;

    uploaded_version_ = snapshot.geometry_version;
    stats_.scene_uploaded_bytes = line_bytes + scratch_.size() * sizeof(float);
}

void ViewportRenderer::draw_images(GpuCommandBuffer& cmd, const core::RenderSnapshot& snapshot,
                                   const core::Mat3& view) {
    if (snapshot.images.empty()) {
        if (!textures_.empty() && snapshot.image_defs.empty()) {
            textures_.clear(); // the drawing lost its images (or another tab is showing)
        }
        return;
    }
    // Drop textures whose definition is gone, so a purged drawing frees its GPU memory.
    for (auto it = textures_.begin(); it != textures_.end();) {
        if (it->first >= snapshot.image_defs.size()) {
            it = textures_.erase(it);
        } else {
            ++it;
        }
    }
    // Every image's vertices go into ONE upload for the frame, and each image is then
    // drawn from its own offset. Re-filling the buffer between the draws of a single
    // frame -- the obvious per-image upload -- is legal GL, but the Intel Windows driver
    // (UHD 620, 26.20.100.x) renames a buffer that a queued draw still reads and leaves
    // the vertex array on the old storage, so every image after the first drew the
    // first one's quad again. One upload before any of the draws needs no such rename.
    struct Draw {
        const GpuTexture* texture;
        std::size_t first_byte;
        std::uint32_t vertex_count;
    };
    std::vector<float> verts;
    std::vector<Draw> draws;
    verts.reserve(snapshot.images.size() * 24);
    draws.reserve(snapshot.images.size());
    for (const core::ImageInstance& im : snapshot.images) {
        CachedTexture& ct = textures_[im.def];
        if (ct.version != im.def_version || (!ct.texture && ct.version == 0)) {
            ct.version = im.def_version;
            ct.texture.reset();
            core::DecodedImage img;
            if (image_decoder_ != nullptr && im.def < snapshot.image_defs.size()) {
                const core::ImageDefView& dv = snapshot.image_defs[im.def];
                if (dv.bytes) {
                    img = image_decoder_->decode_bytes(*dv.bytes); // embedded payload wins
                } else if (std::string full;
                           core::resolve_image_path(snapshot.image_dir, dv.source, full)) {
                    img = image_decoder_->decode_file(full);
                }
            }
            if (img.valid()) {
                ct.texture = device_.create_texture(img.width, img.height, img.rgba.data());
            }
        }
        if (!ct.texture) {
            continue; // undecodable: the IMAGEFRAME outline (if on) marks the place
        }
        const std::size_t first_byte = verts.size() * sizeof(float);
        if (!im.tri_world.empty() && im.tri_world.size() == im.tri_uv.size()) {
            // A polygonal clip: the pre-triangulated region, uv per vertex.
            for (std::size_t i = 0; i < im.tri_world.size(); ++i) {
                verts.push_back(static_cast<float>(im.tri_world[i].x));
                verts.push_back(static_cast<float>(im.tri_world[i].y));
                verts.push_back(static_cast<float>(im.tri_uv[i].x));
                verts.push_back(static_cast<float>(im.tri_uv[i].y));
            }
            draws.push_back({ct.texture.get(), first_byte,
                             static_cast<std::uint32_t>(im.tri_world.size())});
            continue;
        }
        // Two triangles over the (clipped) quad; the quad's corners run CCW from the
        // bottom-left, and image v runs down from the top, so the bottom edge samples v1.
        const auto& q = im.quad;
        const float u0 = im.uv[0];
        const float v0 = im.uv[1];
        const float u1 = im.uv[2];
        const float v1 = im.uv[3];
        const float quad[24] = {
            static_cast<float>(q[0].x), static_cast<float>(q[0].y), u0, v1,
            static_cast<float>(q[1].x), static_cast<float>(q[1].y), u1, v1,
            static_cast<float>(q[2].x), static_cast<float>(q[2].y), u1, v0,
            static_cast<float>(q[0].x), static_cast<float>(q[0].y), u0, v1,
            static_cast<float>(q[2].x), static_cast<float>(q[2].y), u1, v0,
            static_cast<float>(q[3].x), static_cast<float>(q[3].y), u0, v0,
        };
        verts.insert(verts.end(), std::begin(quad), std::end(quad));
        draws.push_back({ct.texture.get(), first_byte, 6});
    }
    if (draws.empty()) {
        return;
    }
    image_buffer_->upload(verts.data(), verts.size() * sizeof(float));
    cmd.bind_pipeline(*image_pipeline_);
    cmd.set_uniform_mat3("u_transform", view);
    cmd.set_uniform_int("u_image", 0);
    for (const Draw& d : draws) {
        cmd.bind_texture(0, *d.texture);
        cmd.bind_vertex_buffer(0, *image_buffer_, d.first_byte);
        cmd.draw_instanced(d.vertex_count, 1);
        ++stats_.draw_calls;
    }
}

void ViewportRenderer::render(GpuRenderTarget& target, const core::RenderSnapshot& snapshot,
                              const Camera2D& camera) {
    stats_ = RenderStats{};

    target.bind();
    cmd_->begin();
    cmd_->set_viewport(0, 0, target.width(), target.height());
    cmd_->clear(kBackground);

    // Scene geometry: re-upload only when the scene geometry changed (not on
    // cursor/selection/snap-only publishes).
    if (snapshot.geometry_version != uploaded_version_) {
        upload_scene(snapshot);
    }
    stats_.uploaded_version = uploaded_version_;
    stats_.line_instances = line_count_;
    stats_.point_instances = point_count_;

    const core::Mat3 view = camera.view_matrix();

    // Grid is screen-space-adaptive: regenerated each frame (cheap -- hundreds
    // of lines). This is independent of scene size.
    // A layout shows its sheet: the paper as a lighter panel with a white edge, under
    // the grid and everything drawn on it (paper-space units are millimetres).
    if (snapshot.active_space != 0) {
        for (const core::LayoutInfo& l : snapshot.layouts) {
            if (l.id != snapshot.active_space) {
                continue;
            }
            const float w = static_cast<float>(l.sheet_w());
            const float h = static_cast<float>(l.sheet_h());
            const float tris[12] = {0.0f, 0.0f, w, 0.0f, w, h, 0.0f, 0.0f, w, h, 0.0f, h};
            aux_buffer_->upload(tris, sizeof(tris));
            cmd_->bind_pipeline(*fill_pipeline_);
            cmd_->set_uniform_mat3("u_transform", view);
            cmd_->set_uniform_vec4("u_color", 0.16f, 0.17f, 0.20f, 1.0f);
            cmd_->bind_vertex_buffer(0, *aux_buffer_, 0);
            cmd_->draw_instanced(6, 1);
            const float edge[16] = {0.0f, 0.0f, w, 0.0f, w, 0.0f, w, h, w, h, 0.0f, h, 0.0f, h, 0.0f, 0.0f};
            aux_buffer_->upload(edge, sizeof(edge));
            cmd_->bind_pipeline(*line_pipeline_);
            cmd_->set_uniform_mat3("u_transform", view);
            cmd_->set_uniform_vec4("u_color", 0.85f, 0.85f, 0.85f, 1.0f);
            cmd_->bind_vertex_buffer(0, *aux_buffer_, 0);
            cmd_->draw_instanced(8, 1);
            stats_.draw_calls += 2;
            break;
        }
    }
    const GridResult g = build_grid(camera);
    const std::size_t minor_count = pack_segments(g.minor, scratch_);
    grid_minor_->upload(scratch_.data(), scratch_.size() * sizeof(float));
    std::size_t grid_bytes = scratch_.size() * sizeof(float);
    const std::size_t major_count = pack_segments(g.major, scratch_);
    grid_major_->upload(scratch_.data(), scratch_.size() * sizeof(float));
    grid_bytes += scratch_.size() * sizeof(float);
    stats_.grid_uploaded_bytes = grid_bytes;
    stats_.grid_lines = minor_count + major_count;

    // Lines + grid share the instanced-line pipeline.
    cmd_->bind_pipeline(*line_pipeline_);
    cmd_->set_uniform_mat3("u_transform", view);

    if (grid_visible_ && minor_count > 0) {
        cmd_->set_uniform_vec4("u_color", kGridMinor[0], kGridMinor[1], kGridMinor[2], kGridMinor[3]);
        cmd_->bind_vertex_buffer(0, *grid_minor_, 0);
        cmd_->draw_instanced(2, static_cast<std::uint32_t>(minor_count));
        ++stats_.draw_calls;
    }
    if (grid_visible_ && major_count > 0) {
        cmd_->set_uniform_vec4("u_color", kGridMajor[0], kGridMajor[1], kGridMajor[2], kGridMajor[3]);
        cmd_->bind_vertex_buffer(0, *grid_major_, 0);
        cmd_->draw_instanced(2, static_cast<std::uint32_t>(major_count));
        ++stats_.draw_calls;
    }
    // Raster images first, under all vector geometry (what the plot does too).
    draw_images(*cmd_, snapshot, view);

    // Scene lines: thick screen-space-expanded quads, one draw per (colour,
    // lineweight) batch. Width is in pixels (zoom-independent). LWDISPLAY off ->
    // a thin default for everything.
    //
    // Two passes when the scene holds WIPEOUTs: the geometry batches first, then the
    // fills, then the wipeout masks in the background colour, then the text batches --
    // so a wipeout hides the line work and hatching beneath it while a label placed on
    // it (the point of a wipeout) stays readable. AutoCAD's DRAWORDER is not modelled;
    // this fixed order covers the "mask under a note" use.
    const auto draw_lines = [&](bool text_pass) {
        if (line_count_ > 0) {
            cmd_->bind_pipeline(*thick_pipeline_);
            cmd_->set_uniform_mat3("u_transform", view);
            cmd_->set_uniform_vec2("u_viewport", static_cast<float>(target.width()),
                                   static_cast<float>(target.height()));
            // HiDPI fix: the framebuffer is in physical pixels, so the effective
            // density is the logical px/mm times the device-pixel-ratio -- without this
            // every line is dpr x too thin on a HiDPI display.
            const float eff_px_per_mm = device_px_per_mm_ * device_pixel_ratio_;
            // Physical pixels per world unit (camera viewport is the physical framebuffer), used to
            // taper the text weight to the glyph's on-screen size.
            const float world_to_px = static_cast<float>(camera.scale());
            const auto draw_batch = [&](core::Rgb c, std::uint8_t lw, std::uint32_t first,
                                        std::uint32_t count, bool is_text, float text_height) {
                // Single-stroke TEXT gets a dedicated, heavier screen weight so it reads crisp
                // and present (not the 1px hairline that looked dull) -- independent of the
                // LWDISPLAY toggle, since text carries no real lineweight to display/suppress.
                // The ~0.5mm weight is a CAP: small text is capped further to a fraction of its
                // on-screen glyph height so tiny title-block fields aren't blocky, while title-size
                // text keeps full presence (floored at a 1px hairline). PLOT is a separate path
                // that honours the entity's 0 weight (hairline), so this never reaches paper.
                // Line geometry keeps the AutoCAD-accurate weight.
                float w;
                if (is_text) {
                    const float cap = lineweight_px(kTextScreenWeightHmm, eff_px_per_mm);
                    const float glyph_px = text_height * world_to_px;
                    w = std::clamp(glyph_px * kTextStrokeFrac, 1.0f, cap);
                } else {
                    w = snapshot.lineweight_display ? lineweight_px(lw, eff_px_per_mm)
                                                    : device_pixel_ratio_;
                }
                cmd_->set_uniform_float("u_halfwidth", w * 0.5f);
                cmd_->set_uniform_vec4("u_color", static_cast<float>(c.r) / 255.0f,
                                       static_cast<float>(c.g) / 255.0f, static_cast<float>(c.b) / 255.0f,
                                       1.0f);
                cmd_->bind_vertex_buffer(0, *line_instances_, first * sizeof(float) * 4);
                cmd_->draw_instanced(4, count); // 4-vertex triangle strip per segment
                ++stats_.draw_calls;
            };
            if (line_batches_.empty()) {
                if (!text_pass) {
                    draw_batch(core::Rgb{static_cast<std::uint8_t>(kSceneColor[0] * 255),
                                         static_cast<std::uint8_t>(kSceneColor[1] * 255),
                                         static_cast<std::uint8_t>(kSceneColor[2] * 255)},
                               25, 0, static_cast<std::uint32_t>(line_count_), false, 0.0f);
                }
            } else {
                for (const core::ColorBatch& b : line_batches_) {
                    if (b.is_text == text_pass) {
                        draw_batch(b.color, b.lineweight, b.first, b.count, b.is_text, b.text_height);
                    }
                }
            }
        }
    };
    draw_lines(false);

    // Filled arrowheads + SOLID hatches: one draw per colour batch.
    if (fill_count_ > 0 && !fill_batches_.empty()) {
        cmd_->bind_pipeline(*fill_pipeline_);
        cmd_->set_uniform_mat3("u_transform", view);
        for (const core::ColorBatch& b : fill_batches_) {
            cmd_->set_uniform_vec4("u_color", static_cast<float>(b.color.r) / 255.0f,
                                   static_cast<float>(b.color.g) / 255.0f,
                                   static_cast<float>(b.color.b) / 255.0f, 1.0f);
            cmd_->bind_vertex_buffer(0, *fill_buffer_, b.first * sizeof(float) * 2);
            cmd_->draw_instanced(b.count, 1); // b.count vertices, GL_TRIANGLES
            ++stats_.draw_calls;
        }
    }

    // WIPEOUT masks: the background colour over everything drawn so far.
    if (wipeout_count_ > 0) {
        cmd_->bind_pipeline(*fill_pipeline_);
        cmd_->set_uniform_mat3("u_transform", view);
        cmd_->set_uniform_vec4("u_color", kBackground.r, kBackground.g, kBackground.b, 1.0f);
        cmd_->bind_vertex_buffer(0, *wipeout_buffer_, 0);
        cmd_->draw_instanced(static_cast<std::uint32_t>(wipeout_count_), 1);
        ++stats_.draw_calls;
    }
    draw_lines(true); // text reads over the masks

    // Selected-hatch highlight: tint the picked SOLID fill in the selection colour so a
    // selected hatch reads as selected (the fill above keeps drawing -- this is a
    // translucent overlay, computed geometry-side). Uses aux_buffer_ (transient), never
    // the persistent scene fill_buffer_.
    if (!snapshot.selected_fill_vertices.empty()) {
        const std::size_t n = pack_positions(snapshot.selected_fill_vertices, scratch_);
        if (n > 0) {
            cmd_->bind_pipeline(*fill_pipeline_);
            cmd_->set_uniform_mat3("u_transform", view);
            aux_buffer_->upload(scratch_.data(), scratch_.size() * sizeof(float));
            cmd_->set_uniform_vec4("u_color", kSelectColor[0], kSelectColor[1], kSelectColor[2],
                                   0.40f);
            cmd_->bind_vertex_buffer(0, *aux_buffer_, 0);
            cmd_->draw_instanced(static_cast<std::uint32_t>(n), 1);
            ++stats_.draw_calls;
        }
    }

    if (point_count_ > 0) {
        cmd_->bind_pipeline(*point_pipeline_);
        cmd_->set_uniform_mat3("u_transform", view);
        cmd_->set_uniform_float("u_point_size", 6.0f);
        if (point_batches_.empty()) {
            cmd_->set_uniform_vec4("u_color", kPointColor[0], kPointColor[1], kPointColor[2],
                                   kPointColor[3]);
            cmd_->bind_vertex_buffer(0, *point_instances_, 0);
            cmd_->draw_instanced(1, static_cast<std::uint32_t>(point_count_));
            ++stats_.draw_calls;
        } else {
            for (const core::ColorBatch& b : point_batches_) {
                cmd_->set_uniform_vec4("u_color", static_cast<float>(b.color.r) / 255.0f,
                                       static_cast<float>(b.color.g) / 255.0f,
                                       static_cast<float>(b.color.b) / 255.0f, 1.0f);
                cmd_->bind_vertex_buffer(0, *point_instances_, b.first * sizeof(float) * 2);
                cmd_->draw_instanced(1, b.count);
                ++stats_.draw_calls;
            }
        }
    }

    draw_construction_lines(*cmd_, snapshot, camera);
    draw_selection_and_interaction(*cmd_, snapshot, view);
    draw_crosshair_and_snap(*cmd_, target.width(), target.height(), snapshot, camera);
    draw_overlay(*cmd_, target.width(), target.height());
    draw_dyn_labels(*cmd_, target.width(), target.height(), camera);
    draw_canvas_command(*cmd_, target.width(), target.height());

    cmd_->end();
    device_.submit(*cmd_);
}

void ViewportRenderer::draw_overlay(GpuCommandBuffer& cmd, int width, int height) {
    if (overlay_text_.empty()) {
        return;
    }
    std::vector<core::Vec2> segs;
    append_text_segments(overlay_text_, core::Vec2{12.0, 12.0}, 20.0, segs);
    const std::size_t count = pack_segments(segs, scratch_);
    if (count == 0) {
        return;
    }
    overlay_buffer_->upload(scratch_.data(), scratch_.size() * sizeof(float));

    // Screen-pixels (y-down) -> NDC (y-up).
    core::Mat3 screen = core::Mat3::identity();
    screen.m[0] = 2.0 / static_cast<double>(width);
    screen.m[4] = -2.0 / static_cast<double>(height);
    screen.m[6] = -1.0;
    screen.m[7] = 1.0;

    cmd.bind_pipeline(*line_pipeline_);
    cmd.set_uniform_mat3("u_transform", screen);
    cmd.set_uniform_vec4("u_color", kOverlayColor[0], kOverlayColor[1], kOverlayColor[2],
                         kOverlayColor[3]);
    cmd.bind_vertex_buffer(0, *overlay_buffer_, 0);
    cmd.draw_instanced(2, static_cast<std::uint32_t>(count));
    ++stats_.draw_calls;
}

void ViewportRenderer::draw_dyn_labels(GpuCommandBuffer& cmd, int width, int height,
                                       const Camera2D& camera) {
    if (overlay().dyn_labels.empty()) {
        return;
    }
    const double dpr = static_cast<double>(device_pixel_ratio_);
    const double h = 15.0 * dpr;       // glyph height (device px)
    const double pad = 6.0 * dpr;      // box padding
    const double caret_gap = 3.0 * dpr;

    std::vector<core::Vec2> fills;     // box backgrounds (triangles: 6 verts/box)
    std::vector<core::Vec2> lines;     // unfocused borders + ALL text + caret
    std::vector<core::Vec2> focus;     // focused box border (brighter)

    for (const DynLabel& label : overlay().dyn_labels) {
        const core::Vec2 s = camera.world_to_screen(label.anchor); // device px
        std::vector<core::Vec2> txt;
        const double tw = append_text_segments(label.text, {0.0, 0.0}, h, txt);
        const double bw = tw + 2.0 * pad + (label.focused ? caret_gap + 2.0 * dpr : 0.0);
        const double bh = h + 2.0 * pad;
        // Nudge the box OUTWARD from the geometry (along the projected `out` dir) so it
        // sits just outside the edge and the fields never overlap each other.
        core::Vec2 c = s;
        if (label.out.x != 0.0 || label.out.y != 0.0) {
            const core::Vec2 o = camera.world_to_screen(label.anchor + label.out);
            const core::Vec2 d = o - s;
            const double len = core::length(d);
            if (len > 1e-6) {
                const core::Vec2 dir{d.x / len, d.y / len};
                const double push =
                    0.5 * (std::abs(dir.x) * bw + std::abs(dir.y) * bh) + 8.0 * dpr;
                c = {s.x + dir.x * push, s.y + dir.y * push};
            }
        }
        const double bx = c.x - bw * 0.5;
        const double by = c.y - bh * 0.5;

        // Filled dark background (two triangles).
        fills.push_back({bx, by});
        fills.push_back({bx + bw, by});
        fills.push_back({bx + bw, by + bh});
        fills.push_back({bx, by});
        fills.push_back({bx + bw, by + bh});
        fills.push_back({bx, by + bh});

        // Border (brighter when focused).
        std::vector<core::Vec2>& border = label.focused ? focus : lines;
        edge(border, {bx, by}, {bx + bw, by});
        edge(border, {bx + bw, by}, {bx + bw, by + bh});
        edge(border, {bx + bw, by + bh}, {bx, by + bh});
        edge(border, {bx, by + bh}, {bx, by});

        // The number text.
        append_text_segments(label.text, {bx + pad, by + pad}, h, lines);

        // Text caret on the active field.
        if (label.focused) {
            const double cx = bx + pad + tw + caret_gap;
            edge(lines, {cx, by + pad}, {cx, by + pad + h});
        }
    }

    const core::Mat3 screen = screen_to_ndc(width, height);

    if (!fills.empty()) {
        const std::size_t n = pack_positions(fills, scratch_);
        aux_buffer_->upload(scratch_.data(), scratch_.size() * sizeof(float));
        cmd.bind_pipeline(*fill_pipeline_);
        cmd.set_uniform_mat3("u_transform", screen);
        cmd.set_uniform_vec4("u_color", 0.16f, 0.17f, 0.20f, 0.96f); // visible dark box fill
        cmd.bind_vertex_buffer(0, *aux_buffer_, 0);
        cmd.draw_instanced(static_cast<std::uint32_t>(n), 1);
        ++stats_.draw_calls;
    }

    cmd.bind_pipeline(*line_pipeline_);
    cmd.set_uniform_mat3("u_transform", screen);
    if (!lines.empty()) {
        const std::size_t n = pack_segments(lines, scratch_);
        overlay_buffer_->upload(scratch_.data(), scratch_.size() * sizeof(float));
        cmd.set_uniform_vec4("u_color", kOverlayColor[0], kOverlayColor[1], kOverlayColor[2],
                             kOverlayColor[3]);
        cmd.bind_vertex_buffer(0, *overlay_buffer_, 0);
        cmd.draw_instanced(2, static_cast<std::uint32_t>(n));
        ++stats_.draw_calls;
    }
    if (!focus.empty()) {
        const std::size_t n = pack_segments(focus, scratch_);
        overlay_buffer_->upload(scratch_.data(), scratch_.size() * sizeof(float));
        cmd.set_uniform_vec4("u_color", 0.48f, 0.78f, 1.0f, 1.0f); // active-field highlight
        cmd.bind_vertex_buffer(0, *overlay_buffer_, 0);
        cmd.draw_instanced(2, static_cast<std::uint32_t>(n));
        ++stats_.draw_calls;
    }
}

void ViewportRenderer::draw_canvas_command(GpuCommandBuffer& cmd, int width, int height) {
    const CanvasCommandUI& ui = overlay().command_ui;
    if (!ui.active) {
        return;
    }
    const core::Mat3 screen = screen_to_ndc(width, height);
    const auto fill = [&](const std::vector<core::Vec2>& tris, float r, float g, float b, float a) {
        if (tris.empty()) {
            return;
        }
        const std::size_t n = pack_positions(tris, scratch_);
        aux_buffer_->upload(scratch_.data(), scratch_.size() * sizeof(float));
        cmd.bind_pipeline(*fill_pipeline_);
        cmd.set_uniform_mat3("u_transform", screen);
        cmd.set_uniform_vec4("u_color", r, g, b, a);
        cmd.bind_vertex_buffer(0, *aux_buffer_, 0);
        cmd.draw_instanced(static_cast<std::uint32_t>(n), 1);
        ++stats_.draw_calls;
    };
    fill(ui.box_fills, 0.12f, 0.13f, 0.16f, 0.96f);   // panel / cells (dark)
    fill(ui.hi_fills, 0.18f, 0.34f, 0.52f, 0.96f);    // highlighted suggestion row
    fill(ui.glyph_fills, 0.90f, 0.92f, 0.95f, 1.0f);  // TTF text (one batch, all rows)
    if (!ui.lines.empty()) {
        const std::size_t n = pack_segments(ui.lines, scratch_);
        overlay_buffer_->upload(scratch_.data(), scratch_.size() * sizeof(float));
        cmd.bind_pipeline(*line_pipeline_);
        cmd.set_uniform_mat3("u_transform", screen);
        cmd.set_uniform_vec4("u_color", 0.40f, 0.55f, 0.75f, 1.0f); // borders + caret
        cmd.bind_vertex_buffer(0, *overlay_buffer_, 0);
        cmd.draw_instanced(2, static_cast<std::uint32_t>(n));
        ++stats_.draw_calls;
    }
}

void ViewportRenderer::draw_construction_lines(GpuCommandBuffer& cmd,
                                               const core::RenderSnapshot& snapshot,
                                               const Camera2D& camera) {
    if (snapshot.construction_lines.empty()) {
        return;
    }
    // A construction line is infinite, so it is clipped to the current view each frame
    // (it is not in the scene buffers, which would be stale after a pan). The visible
    // world rectangle comes from the camera; each line is clipped to it with
    // Liang-Barsky, a RAY restricted to t >= 0. Drawn through the scene line pipeline in
    // the entity's own colour, one small per-frame upload (there are few).
    const int w = camera.viewport_width();
    const int h = camera.viewport_height();
    const core::Vec2 c0 = camera.screen_to_world({0.0, 0.0});
    const core::Vec2 c1 = camera.screen_to_world({static_cast<double>(w), static_cast<double>(h)});
    const core::Vec2 mn{std::min(c0.x, c1.x), std::min(c0.y, c1.y)};
    const core::Vec2 mx{std::max(c0.x, c1.x), std::max(c0.y, c1.y)};
    const core::Mat3 view = camera.view_matrix();
    cmd.bind_pipeline(*line_pipeline_);
    cmd.set_uniform_mat3("u_transform", view);
    for (const core::ConstructionLineView& x : snapshot.construction_lines) {
        double t0 = x.ray ? 0.0 : -std::numeric_limits<double>::infinity();
        double t1 = std::numeric_limits<double>::infinity();
        const double p[4] = {-x.dir.x, x.dir.x, -x.dir.y, x.dir.y};
        const double q[4] = {x.base.x - mn.x, mx.x - x.base.x, x.base.y - mn.y, mx.y - x.base.y};
        bool ok = true;
        for (int i = 0; i < 4 && ok; ++i) {
            if (std::abs(p[i]) < 1e-12) {
                ok = q[i] >= 0.0;
            } else {
                const double r = q[i] / p[i];
                if (p[i] < 0.0) {
                    t0 = std::max(t0, r);
                } else {
                    t1 = std::min(t1, r);
                }
            }
        }
        if (!ok || t0 > t1) {
            continue; // the line does not cross the current view
        }
        const std::vector<core::Vec2> seg = {{x.base.x + x.dir.x * t0, x.base.y + x.dir.y * t0},
                                             {x.base.x + x.dir.x * t1, x.base.y + x.dir.y * t1}};
        const std::size_t n = pack_segments(seg, scratch_);
        if (n == 0) {
            continue;
        }
        aux_buffer_->upload(scratch_.data(), scratch_.size() * sizeof(float));
        cmd.set_uniform_vec4("u_color", static_cast<float>(x.color.r) / 255.0f,
                             static_cast<float>(x.color.g) / 255.0f,
                             static_cast<float>(x.color.b) / 255.0f, 1.0f);
        cmd.bind_vertex_buffer(0, *aux_buffer_, 0);
        cmd.draw_instanced(2, static_cast<std::uint32_t>(n));
        ++stats_.draw_calls;
    }
}

void ViewportRenderer::draw_selection_and_interaction(GpuCommandBuffer& cmd,
                                                      const core::RenderSnapshot& snapshot,
                                                      const core::Mat3& view) {
    cmd.bind_pipeline(*line_pipeline_);
    cmd.set_uniform_mat3("u_transform", view);

    const auto draw_world = [&](const std::vector<core::Vec2>& seg, const float (&color)[4]) {
        const std::size_t n = pack_segments(seg, scratch_);
        if (n == 0) {
            return;
        }
        aux_buffer_->upload(scratch_.data(), scratch_.size() * sizeof(float));
        cmd.set_uniform_vec4("u_color", color[0], color[1], color[2], color[3]);
        cmd.bind_vertex_buffer(0, *aux_buffer_, 0);
        cmd.draw_instanced(2, static_cast<std::uint32_t>(n));
        ++stats_.draw_calls;
    };

    // Rollover (hover) highlight -- the entity under the cursor, drawn beneath
    // the selection highlight so a selected entity still reads as selected.
    if (!snapshot.hover_line_vertices.empty()) {
        draw_world(snapshot.hover_line_vertices, kHoverColor);
    }

    // Selected geometry highlight.
    if (!snapshot.selected_line_vertices.empty()) {
        draw_world(snapshot.selected_line_vertices, kSelectColor);
    }

    // Ghost: transform the selected geometry render-side (move/mirror/rotate/scale).
    if (overlay().ghost_mode != 0 && !snapshot.selected_line_vertices.empty()) {
        std::vector<core::Vec2> ghost;
        ghost.reserve(snapshot.selected_line_vertices.size());
        const auto& src = snapshot.selected_line_vertices;
        if (overlay().ghost_mode == 1) { // move
            const core::Vec2 d = overlay().ghost_b - overlay().ghost_a;
            for (const core::Vec2& v : src) {
                ghost.push_back(v + d);
            }
        } else if (overlay().ghost_mode == 2) { // mirror across ghost_a..ghost_b
            const core::Vec2 dir = core::normalized(overlay().ghost_b - overlay().ghost_a);
            for (const core::Vec2& v : src) {
                const core::Vec2 ap = v - overlay().ghost_a;
                const double t = core::dot(ap, dir);
                const core::Vec2 proj = overlay().ghost_a + dir * t;
                ghost.push_back(proj * 2.0 - v);
            }
        } else if (overlay().ghost_mode == 3) { // rotate about ghost_a
            const double cs = std::cos(overlay().ghost_param);
            const double sn = std::sin(overlay().ghost_param);
            for (const core::Vec2& v : src) {
                const core::Vec2 d = v - overlay().ghost_a;
                ghost.push_back({overlay().ghost_a.x + d.x * cs - d.y * sn,
                                 overlay().ghost_a.y + d.x * sn + d.y * cs});
            }
        } else { // scale about ghost_a
            const double f = overlay().ghost_param;
            for (const core::Vec2& v : src) {
                ghost.push_back(overlay().ghost_a + (v - overlay().ghost_a) * f);
            }
        }
        draw_world(ghost, kGhostColor);
    }

    // Live command preview (rubber-band).
    if (!overlay().preview_segments.empty()) {
        draw_world(overlay().preview_segments, kPreviewColor);
    }

    // Selection rubber-band rectangle.
    if (overlay().rect_mode != 0) {
        const core::Vec2 a = overlay().rect_a;
        const core::Vec2 b = overlay().rect_b;
        std::vector<core::Vec2> rect;
        edge(rect, {a.x, a.y}, {b.x, a.y});
        edge(rect, {b.x, a.y}, {b.x, b.y});
        edge(rect, {b.x, b.y}, {a.x, b.y});
        edge(rect, {a.x, b.y}, {a.x, a.y});
        draw_world(rect, overlay().rect_mode == 2 ? kCrossingColor : kWindowColor);
    }

    // Grip drag preview: the edited entity (computed geometry-side on a temp store)
    // drawn in the hot colour. Lines through the line pipeline; arrowhead fills
    // through the fill pipeline (rebound after, since draw_world expects the line
    // pipeline -- this is the last line draw so order is fine).
    if (!snapshot.grip_preview_segments.empty()) {
        draw_world(snapshot.grip_preview_segments, kHotGripColor);
    }
    if (!snapshot.grip_preview_fills.empty()) {
        const std::size_t n = pack_positions(snapshot.grip_preview_fills, scratch_);
        if (n > 0) {
            cmd.bind_pipeline(*fill_pipeline_);
            cmd.set_uniform_mat3("u_transform", view);
            // Transient overlay -> the per-frame aux buffer, NEVER the persistent scene
            // fill_buffer_ (clobbering it makes hatch/arrow fills vanish on the next
            // non-geometry frame -- the select-disappears + zoom-flicker bug).
            aux_buffer_->upload(scratch_.data(), scratch_.size() * sizeof(float));
            cmd.set_uniform_vec4("u_color", kHotGripColor[0], kHotGripColor[1], kHotGripColor[2],
                                 kHotGripColor[3]);
            cmd.bind_vertex_buffer(0, *aux_buffer_, 0);
            cmd.draw_instanced(static_cast<std::uint32_t>(n), 1);
            ++stats_.draw_calls;
        }
    }
}

void ViewportRenderer::draw_crosshair_and_snap(GpuCommandBuffer& cmd, int width, int height,
                                               const core::RenderSnapshot& snapshot,
                                               const Camera2D& camera) {
    const core::Mat3 screen = screen_to_ndc(width, height);
    cmd.bind_pipeline(*line_pipeline_);
    cmd.set_uniform_mat3("u_transform", screen);

    // AutoCAD-style cursor: full-screen crosshair + a center pick-box. Pure
    // render-side, from the raw cursor -> always smooth, no geometry round-trip.
    if (cursor_visible_) {
        // Pick-box at a constant *physical* size: scale by DPR so it isn't tiny on
        // a HiDPI framebuffer.
        const double kPickBoxHalfPx = 6.0 * device_pixel_ratio_;
        const double cx = static_cast<double>(cursor_x_);
        const double cy = static_cast<double>(cursor_y_);
        std::vector<core::Vec2> seg;
        edge(seg, {0.0, cy}, {static_cast<double>(width), cy});  // horizontal
        edge(seg, {cx, 0.0}, {cx, static_cast<double>(height)}); // vertical
        // Center pick-box (square).
        const double h = kPickBoxHalfPx;
        edge(seg, {cx - h, cy - h}, {cx + h, cy - h});
        edge(seg, {cx + h, cy - h}, {cx + h, cy + h});
        edge(seg, {cx + h, cy + h}, {cx - h, cy + h});
        edge(seg, {cx - h, cy + h}, {cx - h, cy - h});
        const std::size_t n = pack_segments(seg, scratch_);
        aux_buffer_->upload(scratch_.data(), scratch_.size() * sizeof(float));
        cmd.set_uniform_vec4("u_color", kCrosshairColor[0], kCrosshairColor[1], kCrosshairColor[2],
                             kCrosshairColor[3]);
        cmd.bind_vertex_buffer(0, *aux_buffer_, 0);
        cmd.draw_instanced(2, static_cast<std::uint32_t>(n));
        ++stats_.draw_calls;
    }

    // Snap marker: from the snapshot (computed geometry-side), drawn in screen
    // space at a constant pixel size.
    if (snapshot.has_snap) {
        const core::Vec2 sp = camera.world_to_screen(snapshot.snap_point);
        std::vector<core::Vec2> base;
        // Constant physical size: scale by DPR (HiDPI-consistent).
        append_marker(base, snapshot.snap_type, sp.x, sp.y,
                      theme::kSnapMarkerHalfPx * device_pixel_ratio_);
        // Fake a bold stroke by overdrawing the glyph at small offsets (core-GL
        // line width is unreliable). Keeps it one draw call.
        const double o = theme::kMarkerStrokePx * device_pixel_ratio_;
        std::vector<core::Vec2> seg;
        seg.reserve(base.size() * 4);
        for (const core::Vec2 off : {core::Vec2{0, 0}, core::Vec2{o, 0}, core::Vec2{0, o},
                                     core::Vec2{o, o}}) {
            for (const core::Vec2& p : base) {
                seg.push_back(p + off);
            }
        }
        const std::size_t n = pack_segments(seg, scratch_);
        if (n > 0) {
            aux_buffer_->upload(scratch_.data(), scratch_.size() * sizeof(float));
            cmd.set_uniform_vec4("u_color", kSnapColor[0], kSnapColor[1], kSnapColor[2],
                                 kSnapColor[3]);
            cmd.bind_vertex_buffer(0, *aux_buffer_, 0);
            cmd.draw_instanced(2, static_cast<std::uint32_t>(n));
            ++stats_.draw_calls;
        }
    }

    // Grips of the selected set: small filled squares at a constant pixel size, the
    // grabbed/hovered one in the hot colour. Batched: at most two fill draws.
    if (!snapshot.grips.empty()) {
        const double hpx = theme::kGripHalfPx * device_pixel_ratio_; // physical-consistent
        std::vector<core::Vec2> normal;
        std::vector<core::Vec2> hot;
        for (std::size_t i = 0; i < snapshot.grips.size(); ++i) {
            const core::Vec2 s = camera.world_to_screen(snapshot.grips[i].pos);
            std::vector<core::Vec2>& dst =
                (static_cast<int>(i) == snapshot.hot_grip) ? hot : normal;
            const core::Vec2 a{s.x - hpx, s.y - hpx};
            const core::Vec2 b{s.x + hpx, s.y - hpx};
            const core::Vec2 c{s.x + hpx, s.y + hpx};
            const core::Vec2 d{s.x - hpx, s.y + hpx};
            dst.push_back(a);
            dst.push_back(b);
            dst.push_back(c);
            dst.push_back(a);
            dst.push_back(c);
            dst.push_back(d);
        }
        cmd.bind_pipeline(*fill_pipeline_);
        cmd.set_uniform_mat3("u_transform", screen);
        const auto draw_squares = [&](const std::vector<core::Vec2>& tris, const float (&col)[4]) {
            const std::size_t n = pack_positions(tris, scratch_);
            if (n == 0) {
                return;
            }
            // Transient overlay -> aux_buffer_, not the persistent scene fill_buffer_.
            aux_buffer_->upload(scratch_.data(), scratch_.size() * sizeof(float));
            cmd.set_uniform_vec4("u_color", col[0], col[1], col[2], col[3]);
            cmd.bind_vertex_buffer(0, *aux_buffer_, 0);
            cmd.draw_instanced(static_cast<std::uint32_t>(n), 1);
            ++stats_.draw_calls;
        };
        draw_squares(normal, kGripColor);
        draw_squares(hot, kHotGripColor);
    }
}

} // namespace musacad::render
