// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (C) 2026 Pranay Kiran

#pragma once

#include <cmath>
#include <vector>

#include "musacad/core/math/math.hpp"

// POLYGON (issue #23). A regular n-gon is an ordinary closed polyline -- no new entity
// kind -- so the only thing worth sharing is the rule that turns a centre, a reference
// point and a side count into vertices. THE definition lives here so the rubber band the
// user drags and the polyline that gets committed are generated by the same code and
// cannot disagree.

namespace musacad::core {

/// Vertices of the regular polygon standing on the edge `e1` -> `e2` (to its left, the
/// side AutoCAD builds towards); empty when the two ends coincide.
[[nodiscard]] inline std::vector<Vec2> polygon_on_edge(Vec2 e1, Vec2 e2, int sides);

/// Vertices of a regular polygon centred at `center`.
///
/// `dist` is measured from the centre to the point the user is pointing at, and what
/// that means is exactly AutoCAD's Inscribed/Circumscribed choice:
///   inscribed     -- the reference point IS a vertex, so `dist` is the circumradius.
///   circumscribed -- the reference point is the MIDPOINT of an edge, so `dist` is the
///                    apothem and the circumradius is dist / cos(pi/n).
/// `angle` orients the polygon: it is the direction from the centre to that reference
/// point, so the shape follows the cursor round instead of snapping to an axis.
[[nodiscard]] inline std::vector<Vec2> polygon_vertices(Vec2 center, double dist, int sides,
                                                        bool inscribed, double angle) {
    std::vector<Vec2> out;
    if (sides < 3 || !(dist > 1e-12)) {
        return out; // fewer than three sides is not a polygon
    }
    const double n = static_cast<double>(sides);
    const double step = kTwoPi / n;
    const double circum = inscribed ? dist : dist / std::cos(kPi / n);
    // Circumscribed: the reference point bisects an edge, so the first VERTEX sits half
    // a step back from it.
    const double start = inscribed ? angle : angle - step * 0.5;
    out.reserve(static_cast<std::size_t>(sides));
    for (int i = 0; i < sides; ++i) {
        const double a = start + step * static_cast<double>(i);
        out.push_back({center.x + circum * std::cos(a), center.y + circum * std::sin(a)});
    }
    return out;
}

inline std::vector<Vec2> polygon_on_edge(Vec2 e1, Vec2 e2, int sides) {
    const Vec2 e = e2 - e1;
    const double side = length(e);
    if (sides < 3 || !(side > 1e-12)) {
        return {};
    }
    const double n = static_cast<double>(sides);
    const double apothem = side / (2.0 * std::tan(kPi / n));
    const Vec2 mid{(e1.x + e2.x) * 0.5, (e1.y + e2.y) * 0.5};
    const Vec2 dir{e.x / side, e.y / side};
    const Vec2 left{-dir.y, dir.x};
    const Vec2 c{mid.x + left.x * apothem, mid.y + left.y * apothem};
    const Vec2 rad = e1 - c; // e1 is a vertex: the inscribed rule pointed at it
    return polygon_vertices(c, length(rad), sides, true, std::atan2(rad.y, rad.x));
}

} // namespace musacad::core
