# Generates a C++ header embedding each shader file as a string literal.
# Invoked via `cmake -DOUT=<hpp> -DFILES=<a;b;c> -P embed_shaders_script.cmake`.
#
# Each file <name>.<stage> becomes `inline constexpr char <name>_<stage>[] = ...`
# in namespace musacad::render::shaders (e.g. line.vert -> line_vert).

set(content "#pragma once\n// Generated by embed_shaders_script.cmake -- do not edit.\n\n")
string(APPEND content "namespace musacad::render::shaders {\n\n")

foreach(file IN LISTS FILES)
    get_filename_component(fname "${file}" NAME)
    string(REPLACE "." "_" ident "${fname}")
    file(READ "${file}" src)
    string(APPEND content "inline constexpr char ${ident}[] = R\"GLSL(\n")
    string(APPEND content "${src}")
    string(APPEND content ")GLSL\";\n\n")
endforeach()

string(APPEND content "} // namespace musacad::render::shaders\n")

file(WRITE "${OUT}" "${content}")
